### ISSUE TITLE
convert 44.1kHz wav to 48kHz opus, the pitch becomes higher

### ISSUE THREAD

**Issue by Myc123abc** [libsndfile/libsndfile#1007]
I try to use sndfile-convert to convert wav to opus. But it tell me opus only support some specific sample rate. so i force the outfile sample rate is 48kHz which my infile is 44.1kHz. But the result is a little strange. The output file sounds higher pitched and plays faster.  
Then i use opus-tools' opusenc from [opus-tools](https://github.com/xiph/opus-tools). And convert the wav file again, the result is what i want, the 44.1kHz wav convert to the 48kHz opus, and the pitch and playback speed are the same as before.  
These is my use command about sndfile-convert:  
`sndfile-convert.exe -override-sample-rate=48000 infile.wav outfile.opus`  
Is it a problem with the way I use it, or is it something else? I want to know

**Comment by magnus-nomono** [comment]
libsndfile doesn't do any resampling (as far as I'm aware), so what you are actually doing is reinterpreting 44.1 kHz as 48 kHz. That means that for instance a 1000 Hz pitch will sound around 1088 Hz. For the exact same reason the speed increases, as now every second is 1 s + 88 ms of the old file.

**Comment by Myc123abc** [comment]
> libsndfile doesn't do any resampling (as far as I'm aware), so what you are actually doing is reinterpreting 44.1 kHz as 48 kHz. That means that for instance a 1000 Hz pitch will sound around 1088 Hz. For the exact same reason the speed increases, as now every second is 1 s + 88 ms of the old file.

Thank you for your reply. libsndfile does not resample, so I need to manually resample to convert the sampling rate to 48000Hz.
