### ISSUE TITLE
Binary of libsndfile.so for Android.

### ISSUE THREAD

**Issue by fredvs** [libsndfile/libsndfile#363]
Hello.

Before all, great wow for that fantastic library.

I use it in the **uos** project. https://github.com/fredvs/uos
In conjunction with PortAudio, uos + SndFile can play ogg, flac, wav for Linux, arm-Rapsberry Pi, Windows, Mac osX, FreeBSD...

Now the new target is Android.
I do test with the pre-release of portaudio_opensles (opensles is the "alsa" api of Android).
(https://github.com/Gundersanne/portaudio_opensles).

Sadly,  my **libsndfile.so** recognize only wav files (and not yet played correctly with portaudio_opensles).

Here the script used for cross-compiling from Linux 64 bit ----> Android armeabi-v7a.
[android_configure.sh.zip](https://github.com/erikd/libsndfile/files/1734080/android_configure.sh.zip)

And here the Android library-test that I did get with cross-compiling.
[libsndfile.so.zip](https://github.com/erikd/libsndfile/files/1734079/libsndfile.so.zip)

So the question is:
Does somebody have tested libsndfile on Android ?
If yes could it be possible to give the binary file of **libsndfile.so** for Android armeabi-v7a ?

Many thanks.

Fre;D

**Comment by LightSun** [comment]
i have the same problem.

**Comment by SVDpro** [comment]
Hello @fredvs! I've noticed a screenshot of the working libsndfile under Android (#367). I need ur help.. can you please provide an instruction on how to add libsndfile.so into an Android project?
I was building this lib several times under different systems (Windows, Mac OS X, Linux) but still no proper result. There is not much info about how to properly integrate .so file into an Android project.

Looking forward to your reply. Thx!

Daniel

**Comment by LightSun** [comment]
@SVDpro I had met the same problem.  after a day, I found that the build so is in 'src/.libs' .   To integrate '*.so '  you need to include head file and so in cmakelist. then you can write any app to depend on it.  Here is the demo
```java

set(LIB_DIR ${CMAKE_SOURCE_DIR}/src/main/jniLibs)
add_library(media_sdk SHARED IMPORTED)
# path to find pre-build lib
set_target_properties(media_sdk PROPERTIES IMPORTED_LOCATION ${LIB_DIR}/${ANDROID_ABI}/libmedia_sdk.so)

# Specifies a path to native header files
include_directories(src/main/cpp/include)

for link dynamic lib . finally in 'target_link_libraries' you should link 'media_sdk' (for this demo). 
```

**Comment by SVDpro** [comment]
@LightSun thx for your reply. But can you provide the exact steps you made to succeed in this?
I mean the scripts you used, the commands you typed, the dir you set, the cmake file and gradle file, the version of your app etc.

Daniel

**Comment by riku2015** [comment]
I tried compile on linux and it is same what toolchain i use (tried few versions) i got this error even using with cmake. i was unable to find a way to compile this on linux.
configure: error: libsndfile requires a C99 capable compiler!

**Comment by Sarasranglt** [comment]
Can some one provide x86 libsndfile.so compiled for android... Its such a pain building it.

**Comment by mgood7123** [comment]
I think I have a working copy

**Comment by mgood7123** [comment]
Check out
https://github.com/mgood7123/ReSampler/tree/master/android/src/libsndfile

**Comment by mgood7123** [comment]
And https://github.com/mgood7123/ReSampler/blob/master/CMakeLists.txt for
building in cmake

**Comment by mgood7123** [comment]
can confirm successful build and operation
