### ISSUE TITLE
Python could be avoided

### ISSUE THREAD

**Issue by sonoro1234** [libsndfile/libsndfile#433]
Hi,

Thanks for this superuseful library, just did a LuaJIT binding to libsndfile and libsamplerate in https://github.com/sonoro1234/LuaJIT-libsndfile

Python is used in the CMake build for exporting functions in shared modules.
This dependency could be avoided prefixing function declarations with `__declspec(dllexport)` in windows or with `__attribute__ ((visibility("default")))` as done in so many libraries.
Is there any reason to dont use this path?

**Comment by evpobr** [comment]
> Is there any reason to dont use this path?

Binary compatibility.

Duplicate of #213. See #268, #274 for details.

**Comment by sonoro1234** [comment]
It is a long, long story...
Thank you

**Comment by sonoro1234** [comment]
Perhaps they could be pre-generated for each ${SYMBOL_OS} and ${PROJECT_VERSION_MAJOR} (they seem the only variables to phyton script)
And used in case Python is not found?

**Comment by evpobr** [comment]
I told @erikd that it's better to remove all these dependencies, but he's not agree with me. Libsndfile was born on Linux platform, so it was decided to use Python and Autogen in build script. Now we have what we have.

No chance to see changes before next major release. Sorry.

**Comment by sonoro1234** [comment]
Thanks for your patience.

Let me see if I understood correctly: If function prefixes are used instead of the python script, the problem is that executables compiled previously to that change would not be binary compatible with shared modules compiled after the change. 

If this is the case ( and I am not completely confused with the explanations due to my limited knowledge) there will be a moment in the far or near future when another changes done to the library will eventually arrive to a version of the library not compatible with old executables. Should not be this future moment appropriate to introduce the new function prefixes change?

**Comment by evpobr** [comment]
>> ... there will be a moment in the far or near future when another

Hi @sonoro1234 .  It will be libsndfile 2.0. By changing the major number, we can no longer worry about compatibility with previous major releases. Almost without a doubt, we can say that we will stop using symbol scripts to export functions. Accordingly, the python will no longer be needed.

But, considering that in doing so we will break compatibility with millions of existing programs and libraries, this will not happen very soon.

**Comment by sonoro1234** [comment]
Thanks for clarification
