### ISSUE TITLE
unable to package libsndfile > 1.0.28 due to missing chain of trust

### ISSUE THREAD

**Issue by dvzrv** [libsndfile/libsndfile#609]
As discussed in #470 the [1.0.29 release](https://github.com/erikd/libsndfile/releases/tag/v1.0.29) has been done. \o/

Unfortunately the source tarball is now signed by @evpobr (`9B1CFD2E92239C4B288E025F9D0D1F1CCB35FF8C` - btw. the PGP public key can not be found on key servers), while [all previous releases](http://www.mega-nerd.com/libsndfile/files/) have been provided and signed by @erikd (`6A91A5CF22C24C99A35E013FCFDCF91FB242ACED`).

This breaks the [chain of trust](https://en.wikipedia.org/wiki/Chain_of_trust) as neither an additional allowed release manager for libsndfile has been defined (e.g. in the README, using a signed commit), nor has @erikd commented on the release and the aforementioned ticket.

A way out of this situation can be:

1) release the tarball for 1.0.29 in the usual location
2) allow further contributors to the project to handle releases by adding their names and their PGP key to a document stating this fact using a signed (by @erikd) commit
  2.1) make sure to upload the PGP public key `9B1CFD2E92239C4B288E025F9D0D1F1CCB35FF8C` to the key servers
  2.2) define this github repository as the default upstream (or at least as one possible upstream)
  2.3) optional: transfer this repository to an organization so contributor/maintainer handling will be easier for current maintainers

While option 1 is the faster (for this specific issue), I suggest implementing option 2, as this ensures easier handling and faster turn-around-time (in the mid and long term).

It would be really great if this could be resolved, as I am unable to upgrade the package for Arch Linux due to us following [TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use) in regards to upstream verification.

**Comment by evpobr** [comment]
@erikd?

**Comment by evpobr** [comment]
> release the tarball for 1.0.29 in the usual location

Three damn years between 1.0.28 and 1.0.29.

> 2.1) make sure to upload the PGP public key 9B1CFD2E92239C4B288E025F9D0D1F1CCB35FF8C to the key servers

My public key is on [Keybase.IO](https://keybase.io/evpobr). I've added note to [latest release page](https://github.com/erikd/libsndfile/releases/tag/v1.0.29).

> 2.2) define this github repository as the default upstream (or at least as one possible upstream)

http://www.mega-nerd.com/libsndfile/development.html

**Comment by dvzrv** [comment]
@evpobr thanks! now I can at least already verify your key! :) 

@erikd can you please respond to this issue and resolve it (specifically point 2. from my initial comment)? We are now two releases in and I still can not upgrade.

**Comment by evpobr** [comment]
Bad news, i don't have write permissions anymore. @erikd revoked my write permissions after [this commit](b45f0d7d). Oddly enough, not a word was said about my releases.

**Comment by evpobr** [comment]
Project libsndfile moved to https://github.com/libsndfile/libsndfile.

@erikd, could you please update the site documentation? Note in bold text that the project has changed its location. The same about libsamplerate and sndfile-tools.

It would be a good idea to create a pinned issue in each transferred repo.

And also update README, REDME.md and AUTHORS. It would be very nice if this was a signed commit.

It is important that you do this as an author.

**Comment by dvzrv** [comment]
@erikd  can you please add a signed commit to this repository, altering e.g. the README.md, stating which public keys are currently the ones trusted for signing release tarballs? I am still unable to update to libsndfile > 1.0.28 because of this and there are plenty of CVEs fixed with the versions @evpobr released.

**Comment by dvzrv** [comment]
@evpobr I don't think there will be further movement on this topic.
I would be okay to re-bootstrap the trust chain for this package for the sake of finally being able to upgrade.

Would you be able to make sure that:
a) you insert yourself as (one of) the people being able to sign a release (using a signed commit)
b) you establish a chain of trust for anyone that will also be allowed to sign a release (this involves establishing that specific public key in a signed commit as well as signing that other person's key with your key)
c) you establish a chain of trust for your own key from this point onward (this involves signing a potential new key of yours with the previous one)

**Comment by evpobr** [comment]
@SoapGentoo ?

**Comment by SoapGentoo** [comment]
@dvzrv I can sign them, given that my key is widely signed in the WoT. Do you really want a signed release of 1.0.28? That is an ancient release.

**Comment by dvzrv** [comment]
@SoapGentoo 

> @dvzrv I can sign them, given that my key is widely signed in the WoT. Do you really want a signed release of 1.0.28? That is an ancient release.

No, I would like to either establish a chain of trust from @erikd 's key to whichever is used now (which would mean for him to sign that person's key, but that hasn't happened since September) or (more likely to happen) to re-bootstrap the chain of trust for this project (this would mean that whoever signs the tags/releases now would establish themselves as described above).

Background:
The releases > 1.0.28 have been signed by @evpobr 's key, which means a broken trust chain, because to my knowledge his key has never been signed by @erikd.

**Comment by evpobr** [comment]
@dvzrv , i still don't understand. If i create signed commit to add RELEASERS.md, write about me as releaser of 1.0.28-1.0.29 in it, with a note about current maintainer @SoapGentoo and his public key, is that enough?

**Comment by SoapGentoo** [comment]
@dvzrv Also, to be frank, this is mostly security theatre. It's pretty obvious that @erikd has transferred the project at this point, an doing some weird key signing won't really help anyone.

**Comment by dvzrv** [comment]
> @dvzrv , i still don't understand. If i create signed commit to add RELEASERS.md, write about me as releaser of 1.0.28-1.0.29 in it, with a note about current maintainer @SoapGentoo and his public key, is that enough?

That would be much appreciated. This would at least establish yourself and a link to @SoapGentoo (if he is indeed now responsible for signing releases).

> @dvzrv Also, to be frank, this is mostly security theatre. It's pretty obvious that @erikd has transferred the project at this point, and doing some weird key signing won't really help anyone.

I am not sure whether the above statement was meant intentionally dismissive, but it surely comes across as such.
If you don't care about security, why do you sign a release? 
I am bringing this up, not because I am trying to annoy people, but because there is a way of establishing a chain of trust from one key to the next and also to establish which keys are used. Bootstrapping this without a note after the previous maintainer does not answer to a request about this topic for several months is not enough and also not necessarily something I would call obvious. Randomly changing people signing releases, without a document stating who is doing the releases and which keys are to be trusted and no signatures on the respective keys to indicate a chain of trust would rather be the definition of [Security Theater](https://en.wikipedia.org/wiki/Security_theater).

Attacks on infrastructure do happen (also here on github).

**Comment by SoapGentoo** [comment]
@dvzrv I havent checked, but I'm willing to bet that close to 75%-80% of the packages in the Gentoo repository have upstreams without cryptographically signed releases, because, let's face it, the web-of-trust is dead, GPG/PGP has absolutely terrible UX, GPG doesnt pull third-party certifications anymore, noone actually bothers to verify signatures. I've added signatures, if on the off chance that somebody cared, they'd find them useful, full well knowing that it's mostly theatre. What do you do for packages without signatures? You don't add them to Arch? I somehow doubt that.

Back to the problem in question: let's take it to the next level: even if @erikd wanted to sign my key, what if he requires meeting people personally before signing their keys? That will realistically never happen, because Erik is in Australia and I'm in Europe. If I add myself to the `README.md`, how is that different than me signing the `NEWS` file with my key (all my commits here are generally signed)? There's a massive paper trail that proves that Erik transferred the repo. We can change the actual release manager in the `README`, but it still remains mostly theatre.

**Comment by anthraxx** [comment]
you can fully establish a chain of trust inside a repository without the GPG backed web of trust feature by doing exactly what @dvzrv has described: Maintaining a text file in `README.md` or wherever with fingerprints of everyone who is expected to be trusted to issue a release. Any changes to that file (adding new trusted keys) must be clear signed or the git commit object itself  must be signed by the already established keys in the current strong set.

Signatures, be it gpg, signify, age or whatever, are all utilities to achieve authenticated content and are an important part of supply chain security. Basically the only way to be sure content is what the responsible people want it to be. You can't argue against having authenticated sources just because there are packages without authenticated sources. Every piece of software that provides authenticated sources are a step in the right direction. However if a project vouches to be on the responsible side and provide authenticated sources then its the responsibility and duty of distro packagers to enforce the chain of trust is not broken and otherwise expect a potential compromise to be in place.

The main two reasons where authenticated sources make no sense and are indeed nothing but theater:
1) if distro packagers don't care and just blindly accept anything without a cryptographic proof which is nothing but a false sense of security
2) if upstream doesn't properly maintain a chain of trust and expects downstream to just blindly accept new keys without cryptographic proof reducing trusted keys to a strong set

**Comment by evpobr** [comment]
I will update AUTHORS with a list of current maintainers and add note about releasers there. Something like this;

```diff
diff --git a/AUTHORS b/AUTHORS
index b91ec920..bc740339 100644
--- a/AUTHORS
+++ b/AUTHORS
@@ -1,3 +1,5 @@
+Original author:
+
 The main author of libsndfile is Erik de Castro Lopo <erikd@mega-nerd.com>
 apart from code in the following directories:
 
@@ -13,6 +15,69 @@ apart from code in the following directories:
    changes are listed in src/G72x/ChangeLog.
 
 
+Current maintainers:
+
+* Erik de Castro Lopo <erikd@mega-nerd.com>
+* David Seifert <soap@gentoo.org>
+* Arthur Taylor <art@ified.ca>
+* evpobr <evpobr@gmail.com>
+
+Current releaser is David Seifert David Seifert <soap@gentoo.org>:
+
+
+
+Previous releasers:
+
+Version 1.0.29-1.0.30 - evpobr <evpobr@gmail.com>.
+
+-----BEGIN PGP MESSAGE-----
+
+yMMwAnicrVJ7UFRVHF50SdiJ2AknHmYM19IhFrmPva91hnBKHMkcSyAyY7nn3nN3
+L7AP9qVoO5Lja1YUycgJ4iUFWYluTlE4Oi6PxdhpCkesIWiAQIbXqlSs1Ex1l7H/
+6r/OP2fOd77vm+/3za8nZqVCFVEfk/xkgPyrMiLgO+FUFIze8R5AgEUoR3QHkBK4
+fMFSAdod+hJJQHQIiqEYBzECYByBs4AnGBYDGIYDjqEYHMc4nKB5ntICkQSAxCke
+RTEaJ3AthWJaWccItIhyiAYRJbMB2qw2yeyQbVmA8aKAQxbHCZbXApxhIIqTIiug
+AiZiPA8IUhQZXhYaLfawQg4HODvcKFlkTH7ol+P9C/9/zu1cthMJlJG5NM+RFEUC
+nsIomiJIBhMIUmAwNky0Q5uZM0GZDV1WC7Ahbg0iYy6Jh+FaH/4ZJIfRCf6L7yi3
+hoG9EOgfSvVAMgtyd7LCBW12yWJGdJjM5B1SWItpWQwjtBjOahC4zyrZoF4KM0ia
+YlD5aBCrDbpkSxrwIkpwUO6YIHCUAjwOKEIUBFaAIsWKAJfrF7XyoJAGkIaUPD9g
+aSBwIkUIOIqEhykzWxAdKcfkDLKlXTKYOYfTBhF3l2+PUhGhUjwSuSK8UwpVtPqf
+TTv+gVoRyKt70PuZxj6oi7ZkZP481vcc2vJ6cV774dld3s3n3+3w+cXdW9YaVvc9
+ni8Nv6aOUqx5b/+Lexria1wn7c1DOxVnikYSV50eY0o7Lwatz3qqg6RHWVOVF3zm
+lai7u7ud7r7vh5Lrm+95j06OeWN+29SbkNVeW9X1Vs651NsF9K1jV7xzkRdz6N4f
+Vy+5B37qTr18Lclk9lx7o3cmP/+6Jbbl3qvj7w/PvTnVDyYiuxtSZlvtCZ2JT6yv
+21rw8tLXnDHhwv0/7kfnpgSNXxKLA/tyPRsunLxp8tw4e6zx6PGbwsxKsTopg9u1
+dkdzBxWf+VVb/tbUzZNtUzUpj0l1fiSUtu1UaHxwdOnj2JlI4fdfdyAh/5GqvbY5
+7YKy0hgabi89Ffen+qUNtZ+f90258OevKhf6S+p+qelSRh/64ZOihg87D857slVZ
+5wqttfExWb7LymH/oVjTpcWFt4u/uP3pC8YrwfY+ad2NpDuW5oqPZrKOFCoGzqgb
+t1jSF1Vph1c0qtZUds+PaAqpp/Mqhjo0yavKiid91emBiPaeb3s2uW8d9J6YXZiu
+T8p7tK+8yHp3ov4dcCk3lNY28s13ZePrW8ceVGc3zOT01/ibotLjdFZn9tmd67a3
+iCrDaJM7Y/9TY8XzHdPbTZ2wPG7bxFBg2LSx6WootqI1dF2fGutPzE0bzJzW/w3x
+usYz
+=XFTp
+-----END PGP MESSAGE-----
+
+Versions before 1.0.29 - Erik de Castro Lopo <erikd@mega-nerd.com>.
+
+The public GPG key:
+
+-----BEGIN PGP SIGNATURE-----
+
+iQIzBAABCAAdFiEEapGlzyLCTJmjXgE/z9z5H7JCrO0FAljgv0wACgkQz9z5H7JC
+rO2RhxAAnIuHquhkhaY8CVsIOGImMxEF8RKDyFoioV9RnckNzBb592EYxU9hS0MM
+cT6xPZU0bJa8CvmCxEABMlkk60JP4VmmOtWxD8EEyktbHGyao80mDR82yVKYv78L
+zTRzz/JoTncgwWz/QataMbkAfy3KpxkwDW87az0kzkqGuSm3Jg3medt+t/iBe0Wm
+jcxIexxEZCmIhty6VyaVEkGWax0zdJHe7aD9FK2C/R3DU5Byp4e9pcp/a8v74G1n
+dgD4S3YlqvJGuU9S6QD4PzsoWD1X8f6pHzxpRP/OkqHAe11sSRo6sSYYCjsYi9Ca
+IJSlVC1nMx9OUxxAA8ZqtnztOo7GZcJ5NAL5X3GNV6YfQ7Bqxvtr6QG26F06MB6i
+p08UC7NC0bxFsD3f07wY22QnbnM052rniTn5sqQZv+GVls6t1b3u1iHzEjAjlgvi
+eOjVVt/A8iaOzMbKC/3+SZ9/GYqbSAQOCIoWAXmhV9IaMQyQeLCIC1YD5NMGBXal
+HPfSHV0hSUDbKjAYXFigJRzFU125bXTgg+v13Kd0KklIEjoaZYZLAYs0BupXdjBf
+jSPv8pwUaXJkv9/bGH0Ot1fvwDqPDOlGFINQbGAWdxwsdhiYBeXMFeFNTEfiqEMz
+BhhMxKa+Mfd9fkrX4NNigGW5QgRBS+FHNLf6ZfiXSnBGjjxMcbI=
+=UUA0
+-----END PGP SIGNATURE-----
+
 Others:
 
     2013-03-07 Michael Pruett
```

We can't count on Erik, apparently he is completely immersed in programming in haskell and does not want to waste time on this project. That's all we can do now.

@SoapGentoo , i'm too lazy to search you public GPG key, can you post it here.

**Comment by evpobr** [comment]
As far as I understand, we can't establish a chain of trust without Eric's involvement, so I think further discussion is pointless. I guess that Erik has completely immersed himself in functional programming in Haskell and is happy to take a break from the project to which he has devoted more than 20 years.

However, it is worth reflecting in the documentation the fact that @SoapGentoo is the current releaser. It is also worth continuing the practice of signing release tags by the release manager. On the GitHub Releases page, I suggest adding information for verification for each release. For me it was;

The GPG signature is at [Keybase.IO](https://keybase.io/evpobr).

@SoapGentoo , can you post your GPG public key here.

**Comment by SoapGentoo** [comment]
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQINBFppABgBEAC42ZiNvV7BTIgR6TQy0YnF54fx3mVRP1u8Mq00UZa7reAsNKh7
1H60j0W4s6+4pVVIKGfpVGxLwUdJe+KVCYw1Cd3YW6uMf5zZrC/ZWqnJiH/n6S6o
1l4INII2o6YbGBnzIWBPRo7PlOL+mvgKTLpBSJPnhD8XDGN5wRiV8rL2+6Dptg0F
nJt7oxECGF3OD3gk6HMel0o82CVkIqMtNaX1L/bhcdF7K0Rp2MXPZMmpn1izW5sI
asN1G9+w+Zwj7kMJzq1Aw3ac+rsX4SEYdvXjS2QhDHQUIr6LXri3D2WbcEqIZj2R
JVoVwblsrG11dYXFDBbgrq4NhgTBsxHYDlkr/qF2W+kbPC/nhSqTVZeCYvTBZbOQ
+RqyN/I0izukglnWmV1jGijFA8snyP8efx732hw/24zRYmtXOtnEITUpw8WOeZCq
6uiHaQ+eopnY2ojBg9BI7WZm0AFn58xxT9soMsyFOUFgXTqaWFZWlJ3fhZE8/0v8
JEu/kPGE5aJReT3b34B+Bojkj74XR+h2u7iJJBHMTE8RwGoUOZHer/XsL9xlcdks
I+7TCjiq++ShaSSt2XsJmw2BhREohrjW/2KkwmvT3b44RMpKPB4WTH+++aqJQNeM
IqmswOMoZvzEZezInj7WVY/r0WEei1Y6wt1tBrJ/cFf1oQBM1UmphxcrfQARAQAB
tB9EYXZpZCBTZWlmZXJ0IDxzb2FwQGdlbnRvby5vcmc+iQJUBBMBCgA+BQsJCAcD
BRUKCQgLBRYCAwEAAh4BAheAAhsBFiEEMdlcq22A0mIkShdQpHYg6AHkfpUFAl/V
CvoFCQkuceIACgkQpHYg6AHkfpXYxA//aiJW1NwunpmzEc62id8lRMnoLHWVjISZ
b+xSlm+hk4LYq+ZbthJDzKcT86/3DJOSE1zQw9wLuCao9IW2UfFJQBtR+TAfbagG
0Yyk/kMcLoFJxnG1ywdJWypCAauuIhia52Z7PmmjsBbFwr6LygDwSQmZAyACMAs7
TLQe+yERc2RNDsIEsquLSxxRF0Spk9gagWtKgrPc2XBjuNtQDwW7JgsOUoEeHyxC
29fRUjC3o/pG2I6iAZp17OROZI5yl4TSORrSBDGIi2sayxyxP0x+IPKtrCUcBGNx
wGp+56bP/V0hA6sgCPh/iwvqLoeibso6l/Kd4ltVAEQnHTd6fr8g+wLEUXfbJVTR
7aeFUoaFmWjSPlQrNr6HlxSLV/kRx9kVJp1Pn16vkfVBF7fG7iDLiqphwEeQg5ND
nmGeKAbRRNxFHyBHf0XRsaYiFZQckguO+71XSRtVx8/YP5nyNbtl9y1h/4JlT6Gy
t7hb5twYFQyQrKss83E/Bo1sRdHpj0ibtqb4ZbYANbh482E6yFhAkuo8YjVTJipI
1Ve8EBKnX3R+pDt147uyysNvtPVXML+sWpGSMVSm4NA8uT3F5nqxVwj+SeXy3Wq/
CHQ2VBKGBC655G+wFD5C6O7cTx2MwH+2H8tzhWm+gFlI3MFKEXa/PC+YUC/diYcb
BrApavriTRa5Ag0EWmkAZgEQAPXMD3mZI+ChvBysXZWksC88/uSEwFeb3XkcRm7v
04GN7hcz+bfrmnUTB3tuE/ZQgv+u7ZjetvH1aEKieznn/GjnWoOBoJusOYvfAQeF
0mQVi118QiOZRCnEZpkz+RY9TiXVgrZJg+AGqHZ3Ol4GkInEV2NWgH37Xal+HkFl
rwI2U7mL0kZRG+LAVCQHKzqU0R0HE1XyJ4qf0awtG5Qi/TZvgXBdZPDXgr8i9Vlf
UUu10c2XnXM0Av/YAlZmBFjVYrSOUCFenqSVqL+s9sTCVdWlJrGjrr3Ja4uT3kl2
rLva0AR4oSQoxt8adKohmFz0vzOkQtCoRzhrCwoo3JvNjKdSNoOP1nSsxlO5ji8r
ih5d+ajPgi580XyHLnrvG7vobR48qqscv1hizKuCgTacOTe6Db2Gqc8xF6v8HhJa
KwWJtmFllIfN/tIvZ6BbbgHQn0IGf4CYnWf0SksPZqpBmTRpD2jfBxcj2UEg+AR3
LARjuyUVpFJScyu6ExQG+6O+ByLL31iWP5MgUrza1rIpriPa3NT3rZ3DG2pvQrS3
ySsrPzH7VRX8L1ThSMSzjwF96aMsd14s7XzR4EzNuWwZDukfs0yavZk6l4o1M0mb
tbJi7hE4cz13KRHYvIkKMdZGYUnzRzZUDlsj2imakk3BR6GXnxZ1ST6062g+QxiL
AJFLABEBAAGJBHIEGAEKACYCGwIWIQQx2VyrbYDSYiRKF1CkdiDoAeR+lQUCX9UL
DQUJCS5xpwJAwXQgBBkBCgAdFiEEuNUxXaAAcsCoYIifzjbhFyAuOEIFAlppAGYA
CgkQzjbhFyAuOELmrQ/9H9wrWsWa21STZdxUmyU2sh9VXAWEHl1Ey0fVTznDM0Fl
zx5YSR/TmmnE36rpaz31Ttkx8SP914oV+mMgseecdya9Bf6uZL9Cv7V3KEsJBRL/
ncrOWQBHP/Xy1X+mLD6A19xq7H4RihSLj0LeK2YVjrJzJ7wMf4mKXuBayQeAHImU
WRCRTbmK3umh2nB5V0iPd/XZEIiYtiTPe+7E/va6+0bBvOumF3a+Z0iui7eU4hFC
7Jk71D0dcg09SlIaNoMOrw7cMC3j2pMdKtsj8+0I6WBv14PhhqPAsnjdf7I/4NfK
L7Jav8T/gDS01uA2Jxm72d+wr+eSjOBXa6x8CEbTqfkjAGxsWENThCp6zDkaXSDd
JsV0va47vjzG8+wTDAvPy5IxIM/KZZdl4uWM+mF5K+q+eSTOHe7aLF2OdcussoBA
A18zm994dAkG1COX/qpxanxx2bv/2IvCGPg+x6JtAN8ji2kncWu3dWGQdE5XbVjc
fDwgsUPpp04G27Mr/x+HpEbgZ5SdA0dAqJktlNvCcHALhlblCWrsh/1QNjT/2iG8
wsjcpEy/s4tWAuV4PTa4xvZ1JPS7Z7Eo5aBy9ZGOWG9SrHEiHnhkUsiswbHBOEjd
pBSkmNElDcv9fRUahVCTPfvWBATFDrQyMjJBSm+cV8c/iFQM7isVSu8W7E0eetsJ
EKR2IOgB5H6Vv9sP/1dxTvH0N0UoEoxIG/hnirEkbRpljdvqy4/uikYBKyQgSbo8
VITTjea7gIhDztil9WZYt35jbOmoaGM2Z6TP2LEDOWgljYUNq9pl9Sc2GS8cNtEO
WxExzGOc1Flo730dX3A85Ks3+0WPXZjLDcRRcPVkFd5WLQQDV1YVYopWkuQBC+Br
4q3uv+sk+bw6gDa9+zFBbDuegdsYuTXrFHoxHz2GRv9Yb7ULCMgpFeNKDgtQq91u
RqewoTwQp9tlp91LH/hh7R0Q4DRgeFDkLnVRXwSKjVvCrT5cBgImGwtFTGS4egoy
MDKd/KKjZllp1ahRCln1XfmFQyQVMVvuF/JTtt31n6KwXwK2yxIlXB01xvRH+Ees
AWeRYWKWXydaAY/9Ve0/PLFlgsr/XUGvt0GoEKe7odD3nZgg6015+/8JTroKw19L
NZkhdfFMl11Zi0j5k3UbyzjYVpFSd8K2o0VoOG1LFsPp8tlRxNoVzpId0CX1au/p
y1H7Wy/39mzriRG3rw+mJAQbBjN09putCltXFXpOEWk08n/N3vufCVQUoSu/2Bqw
2HYj8VtToQp+O5dG3XxvDHINtInP1yr2Wcw2plna0KoXLwv/lZgDm3LN+eCWpG6d
N/xk25DTSqTHArUQIEkhcHYK6GnyxUcvoKtG88hXtqEPYXiK08FZYAUPTnDYuQIN
BFppAIkBEADDjvQZUs1NoqJpxkD2QDBudU1DBCaeI1D6CancMtb5FebPUxgFlDMd
CBGOun48dY5i87gDhT/qS3gP/Mv9rjKJmcG9JHfhpXdW73owxrcsQ96nxxVJNEVl
UHJw00z8C9eGWqr0SzSoE33K/PkzSkgtsaotF6+3uCerWulweulmGa5dpVfV0mbS
aVw8VmrhZ5NmCeodyy/lR85rPik5pb32NT6v7xBkgkfS0VYtPB2E5gW1pXX/jEOi
Mfq9idOEP9lxrNXV9j49Lr0JQCwAcrYbQ2+VPe6eacJEjzJ/6HiUqhPrYdnvydmb
hU+xmv2NjGp2UnDZDEhzQfwm6fMx+8Nx2uPzCnXQGoyRBwiC/KcdW0F1ZPKdSXqH
NKoOF62pLvIMSmfI3ZVOrTohArfr1kFEYVDv9Nl7oY+qg2rZEc2srOF74a9Z46bR
TDPsEQzE2UMCvu3+rofhSD7aRotlKeDCvbe2s0yE4Man457Xc3LXh8Gva8CzCOLE
2eMhNTsHIZk68WgXp3/uvE4Xy42myrk1AV8XXDdlWgx0Kc/I6tE59O5NVPSfuGvH
1a15KKx0F6euEnYDKKpQ5PDR6dSn61po0tfbt96m044G/xQFjrfhHei4jji9Ogd9
vlXVAi2vn3+NCSHFP5l3igLByBHy9iLIdmz7yQuus/1nwRmxOHOf2QARAQABiQI8
BBgBCgAmAhsMFiEEMdlcq22A0mIkShdQpHYg6AHkfpUFAl/VCxkFCQkucZAACgkQ
pHYg6AHkfpVPSRAAmheYkYJmtDbkzPBBnj5mbCIQN1/G5PI9eixc/TXWFOXtcjU1
mJlJpSidHJyLRrx7r0c+N+s8vnY/JuUBsNoMJMER+Mv/CFW4iFi59V534SyAb2S0
7NINJnFNkXBY62CDz9KsMuv/MdSv2yLhPH2Tfrm/eDRQesj1PanE4U1cgjWyJRc/
IOlaRHvTasWDLgwbQi8ykt+4xUWzL/YKHzB+KyyzBK7vPBXqySX8ka4BOw7SDwG5
lX2gtmhk4AGBwVChLXKflqVx1WXj4DPOt0kmOKVnKFyvUijK58M0A2FMgFMXDTIS
DRtoZPdx/rkODXxgS+W+27NcYAnxJiM0cQqizEnQh7PQ1KzgdChPejYXMKe9lwdn
ssMUxrBpbuAuagEf+pebNjD2eaNR4p8kfaDdGn53q55ysDvoyxKvnVQGSk1FAR9Q
s4N5a4f02U7dzlyEhEfIcuUlRCfnlpn4n725YIhHheDig5zKWoEZCkNIfiRcGzDl
8Drj+tlZiUR+gDkIoWSBaCkKbIQlc8qCYy6Hm7oZBaol6xKlUnTMK2rjK8fR4i8r
bVDWBAaWj3jcDHJ0Jg3fS/qBpeya/JXMp89TR8NK5Ys7PZpWbor+puXBYyXDAVx3
rXQ7JBA5klHPxrgjso1S/LqwscKLENtrVjdjhryLBmPifrmofJRnrpiHIEa5Ag0E
WmkAswEQAL0hKwsRybQzkNGpJP+ElLSwFHd7XQhr+qIwLllpumWtnIK/DHmv8SpW
FqAYajmRTXipFcBHH25x2jIIliZidn0a9826l+sMzrFadMC6/W4pitP71TeqZzwn
pAuHs14YL7Wiy0aJQnfbCpRzPq3kYyOXmhmY7lPWO0WdUpR6W8wUbleK5XOVDDRx
aIC/M3hhDOxZOMzQ+pdn4BaOFQQ0ygsRkqOudbuc0R1giYRt1i6gMeT8gfzL9jlw
HcJ+aVnxdUQQ4uC47oKo/+lg7qh7LsiW79pQC1Bcdm8lhRmqtxe6ub60ecjax3XU
1ILIEfIFCv6M7LRUAwz0bqk35spgkJqrGGKkdeWEKAFHg2QWR2F0zy+HdlPLfKxO
uhaccpwc9EJtf744GS0SXa2AXr32j56n7CFcEjFcIQPBC6OJn6eA3hOVUYGZ7SrT
4fsmZiFAdGEkvLKFuNhju1Hj2EJQUY1pm4GSBco7BR8x+QqoYrt5clU3WxRMNfTR
0Rtuzsh4xskXNVMMgvKOahAtxENv2M2Cx6zJPVL5dmaysP7d6QRVeOQA5PwkcZ5Q
qK6JtDZj2jpaKQH4Za715kiIcdqMDSkwxa6avc0kARHvfFcBR4hwDm1GAlaKG7eH
8TOGGQIk8x2F3s4l8mTJVLWTP/uJYnkYBdqANYo5t1NIQLvwLFV3ABEBAAGJAjwE
GAEKACYCGyAWIQQx2VyrbYDSYiRKF1CkdiDoAeR+lQUCX9ULIwUJCS5xcAAKCRCk
diDoAeR+leekD/sF7aHH0W35ckWrXZlfSp0qHPWrBUaLBI9OAUHenRhgs4SbK0D4
wqEiu0C5iDQojpXAeALQ8g/1pUsZ1yuFqYbGYWrHkA0Pm+P3tAGB4LMZ41YfvROP
uaiW/+IMJbWllgRtaDt8/NtCgs30WI9I+az5M29HcGfvEwEUykrBx3dE9T+1ui3O
capdd+GMvdAAsX5PyVkjWgZ7GrZeH8mG7UysYfT4qthxEtQfZ/u8ceSduKA46ugh
C2eafIDNvluqn7BU4oKxME61u6C8BN2yHLI6LV0Tr4z5H8joVbM4BSFMwLVGlsXf
HhB8kLiErN6bXolxsjARlmYiD9S9H2AcYidr6RYXf2EVFSpBG59xn1WTDN+DsHQf
7btNPEPl/OPxa3OQjG+xn8USddiP0N0B4xsyzMNCCKDgvXXcIhX55KG9eh3Tc98S
fEyhxu8ybZBIGmTJysPKxijfvSgQF+RPNTsz9lvXqkoK7RTgeYMschpjJEznCLbt
M6eTDb5z0G5uLXh6+dYxtDOlPogI5OHd+G51LwCjvrQ+AtIUCgafuemwA9mpFT2b
svb/qcxSVUb44bVaNHn1JHebX2YbokGtBOm1x2PI5fT8n6YIIYz3jKYOZAYdUT7x
6qURyNjOfG4aPJIATwuh4GSNuxUG40+yuT+XfQF24mu1esS1J3wzRloJ7w==
=K3x+
-----END PGP PUBLIC KEY BLOCK-----
```

Located at https://keys.gentoo.org/pks/lookup?op=vindex&search=0xA47620E801E47E95. Given that SKS is broken beyond repair, I'm not sure posting a link to an SKS-linked keyserver makes an awful lot of sense, but it should be there as well.

**Comment by evpobr** [comment]
@dvzrv , i guess it is all we can do at this moment. Thanks for the information, I learned a lot from it, although my knowledge is still at a basic level.

**Comment by dvzrv** [comment]
> As far as I understand, we can't establish a chain of trust without Eric's involvement, so I think further discussion is pointless

That is only true in so far as the connection between him and you is concerned. You can (and should) still establish this for yourself and onward (it is literally as easy as adding a document with the key IDs in a signed commit, similar to how you outlined [here](https://github.com/libsndfile/libsndfile/issues/609#issuecomment-764764472)).

Without it, the signatures are pointless and you might as well not do them.

At any rate, thanks for looking into this!

**Comment by evpobr** [comment]
Like this commit?

6a3df24db46ae48955138419fe1ce46de1f78c37

**Comment by dvzrv** [comment]
Argh sorry, I didn't see that commit for the AUTHORS file :-/

For brevity, you can use the respective key ID (see `gpg --keyid-format long --list-keys <mail address>`) instead of the entire public key:

* David Seifert <soap@gentoo.org> `31D95CAB6D80D262244A1750A47620E801E47E95`
* evpobr <evpobr@gmail.com> `9B1CFD2E92239C4B288E025F9D0D1F1CCB35FF8C`
* Erik de Castro Lopo <erikd@mega-nerd.com> `6A91A5CF22C24C99A35E013FCFDCF91FB242ACED`

The way you provided it is also fine though (just a bit more tedious to get to the public key).

Thanks again!
