### ISSUE TITLE
Future improvements

### ISSUE THREAD

**Issue by evpobr** [libsndfile/libsndfile#624]
@erikd , @arthurt , @SoapGentoo 

So, we need to solve a few questions.

1. Who makes releases.
2. GPG key to sign releases, who generates and owns it. 
2. Where is documentation. Is it http://www.mega-nerd.com/libsndfile/ or we use https://pages.github.com/ or something else.

**Comment by erikd** [comment]
For the documentation I would be happy for it to move to where ever is most convenient for the people who maintain it.

**Comment by evpobr** [comment]
> For the documentation I would be happy for it to move to where ever is most convenient for the people who maintain it.

You can test it here: http://libsndfile.github.io/libsndfile/.

It is just starting point, still need to update few things.

If it is OK, add redirection from old URL to that page.

**Comment by SoapGentoo** [comment]
@evpobr I can make releases. It seems that while bootstrapping the latest libsndfile tarball, you changed one bash script from LF to CRLF (which breaks Bash). I have a very high connectivity in the web of trust (not that anyone really cares anymore) and can also sign releases.

**Comment by evpobr** [comment]
> It seems that while bootstrapping the latest libsndfile tarball, you changed one bash script from LF to CRLF (which breaks Bash).

Oops, it was not real Linux, but Debian in [WSL2](https://docs.microsoft.com/en-us/windows/wsl/) under Windows.

> @evpobr I can make releases.

Ok. @dvzrv, what do you think? Still need @erikd to prove it?

About Windows packages - i will add Windows [artifacts upload](https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts) to GitHub Actions.

**Comment by SoapGentoo** [comment]
@evpobr mind me updating the tarball (so I can remove the CRLF patch in Gentoo)? You can produce the signature or I can.

**Comment by evpobr** [comment]
Of course update it. I guess it's better if I sign them to avoid confusion. Moreover, the commit and tag of the latest release are signed by me.

**Comment by SoapGentoo** [comment]
@evpobr updated the tarball (and deleted your signature), please resign!

**Comment by evpobr** [comment]
Done.

**Comment by evpobr** [comment]
Wat about 1.0.29?

**Comment by SoapGentoo** [comment]
nah, 1.0.29 has the broken BE stuff, we'll skip it in Gentoo

**Comment by evpobr** [comment]
Github Actions failing, it is [MSYS2 issue](https://github.com/msys2/MINGW-packages/issues/7084).

**Comment by evpobr** [comment]
All three sites moved to GitHub:

http://libsndfile.github.io/libsndfile/

http://libsndfile.github.io/libsamplerate/

http://libsndfile.github.io/sndfile-tools/

Note that the gh-pages branch is just static storage and is not updated automatically, and all files are located in the root, not in folders, as in the master branch. Therefore, to update the site, you must first commit the changes to the master, then switch to the gh-pages branch and commit the changed files there to the root. After the commit is pushed, the site will be automatically updated.

@erikd , can you set up a redirect from your site?

**Comment by Be-ing** [comment]
Thanks again @evpobr for putting some love into this critical infrastructure. :heart:

**Comment by hardfalcon** [comment]
Could you add the older "official" release files (for example Windows binaries and signed tarballs) from http://www.mega-nerd.com/libsndfile/files/ as assets on the releases page of the Github project for archival purposes? Right now, for versions <=1.0.28, the releases page only offers the tarballs and zip archives generated by Github.

**Comment by evpobr** [comment]
I think this will create more confusion because previous releases are signed by erikd. In addition, not all previous releases have tags, and erikd should make them too, signed by author. If he wants to do it, I will be only too happy.
