### ISSUE TITLE
Issue compiling whilst on musl.

### ISSUE THREAD

**Issue by purringChaos** [libsndfile/libsndfile#627]
On musl, the check for ssize_t fails. 
This leads cmake to insert "#define ssize_t " without anything else at the end.

On musl libc ssize_t should not be defined manually or else unistd will break.

**Comment by purringChaos** [comment]
This is also a issue with autotools.

**Comment by evpobr** [comment]
Hi @purringChaos 

I need more info:

1. libsndfile version
2. CMake configure log
3. Generated config.h
4. CMakeCache.txt

**Comment by purringChaos** [comment]
issue cannot be reproduced on latest commit of libsndfile, seems to be fixed.

**Comment by evpobr** [comment]
Ok, no problem.
