### ISSUE TITLE
File in memory

### ISSUE THREAD

**Issue by Adrian-Blandin** [libsndfile/libsndfile#656]
I'm looking for a way to write a file into memory and I can find the following Q/A in the [website's FAQ](http://www.mega-nerd.com/libsndfile/FAQ.html#Q009) \:

> Q9 : How about adding the ability to write/read sound files to/from memory buffers?
> This has been added for version 1.0.13.

I've not found anything related to this in the API documentation, website or anywhere else. 
Is this functionnality implemented ?

In any case, it would be helpful to update the answer to this question to indicate how to do it or that it wasn't implemented.

**Comment by evpobr** [comment]
I guess it is [Virtual File IO](http://libsndfile.github.io/libsndfile/api.html#open_virtual), added in 1.0.12.

**Comment by Adrian-Blandin** [comment]
Thanks! :)
I'm not closing the issue, because I think the FAQ should still be updated to point toward Virtual File IO.

**Comment by Adrian-Blandin** [comment]
Also, I would propose to add something with the word "memory" in the API documentation, because searching for "memory" is the first reflex that a colleague and I had.
Maybe doing the following changes ?
> This is usually used to interface libsndfile to a stream or buffer based system
to
> This is usually used to interface libsndfile to **write/read from memory with** a stream or buffer based system
