### ISSUE TITLE
Performance regression writing WAV files

### ISSUE THREAD

**Issue by krisfed** [libsndfile/libsndfile#660]
Hello,

After upgrading from 1.0.28 to 1.0.30, we noticed a 150-200% slowdown in our workflows for writing WAV files (on Windows). Are there any known performance issues that might be related, or bug fixes\enhancements that might have resulted in worse performance?

I am working on creating simple minimal reproduction steps, and so far I can reliably reproduce ~50% slowdown with the following minimum code, specifically measuring sf_writef_double part of the workflow:

```
#include <iostream>
#include <chrono>
#include "sndfile.h"

const size_t frameSize = 65536; 
double data[frameSize];

int main()
{
        // open file
	SF_INFO fileInfo;
	fileInfo.format = 65538;
	fileInfo.samplerate = 44100;
	fileInfo.channels = 1;

	SNDFILE* file_sf = sf_open("test.wav", SFM_WRITE, &fileInfo);

        // write WAV and time it
	auto begin = std::chrono::high_resolution_clock::now();
	int j;
	for (j = 0; j < 3000; j++) {
		sf_count_t framesWritten = sf_writef_double(file_sf,
			&data[0],
			frameSize);
	}
	auto end = std::chrono::high_resolution_clock::now();
	auto elapsed = std::chrono::duration_cast<std::chrono::nanoseconds>(end - begin);

	printf("%.5f milliseconds\n", elapsed.count() * 1e-6);

	int error = sf_close(file_sf);
	return 0;

}
```
I am getting on average about **795 milliseconds** for 1.0.28, and **1178 milliseconds** for 1.0.30. 
Does anyone have any thoughts, or noticed similar performance regressions?

**Comment by evpobr** [comment]
Hi @krisfed. 

Do you build the library yourself or download it from somewhere?

**Comment by krisfed** [comment]
I have tried both the prebuilt 1.0.30 DLL as well as the one that we are building. With prebuilt DLL, the regression seems a bit smaller, but still about ~30-40%. Still looking into where the rest of the regression we are seeing is coming from.

**Comment by evpobr** [comment]
The official version 1.0.28 was compiled using the GCC compiler, and versions 1.0.29-1.0.30 were compiled using the Visual C compiler from Visual Studio 2019. 

I have a suspicion that the compiler from Microsoft optimizes our code worse.

**Comment by krisfed** [comment]
Thank you for taking a look!

Experimenting further, I noticed that performance difference is **much more** significant (>10x slower) when the data to be written is initialized to non-zero values. Here are the mean values I am observing:

|                       | initialized to 0 | initialized to 0.5 |
| ------------- | ------------- |  ------------- |
| 1.0.28 release | 718ms  | 719ms  |
| 1.0.30 release (prebuilt) | 1054ms  | 11896ms |
|  1.0.30 release (built by us) | 1103ms  | 10631ms |

If it is due to compiler switch, I guess there isn't much we can do. There wasn't any significant source code changes for writing WAV files? But I am curious if anyone else is seeing significant slowdowns in writing audio files after upgrading, or at least can reproduce what we are seeing. 

Here is the latest version of repro steps I am using:

```
const size_t frameSize = 65536;
double data[frameSize];

int main()
{

	SF_INFO fileInfo;
	fileInfo.format = 65538;
	fileInfo.samplerate = 44100;
	fileInfo.channels = 1;
	fileInfo.frames = 0;
	fileInfo.sections = 0;
	fileInfo.seekable = 0;

	int k;
	for (k = 0; k < frameSize; k++)
	{
		data[k] = 0.5;
	}

	int i;
	for (i = 0; i < 25; i++)  // repeat the experiment
	{

		// open file
		SNDFILE* file_sf = sf_open("test.wav", SFM_WRITE, &fileInfo);

		auto begin = std::chrono::high_resolution_clock::now();

		// write
		int j;
		for (j = 0; j < 3000; j++) {
			sf_writef_double(file_sf,
				&data[0],
				frameSize);
		}
		auto end = std::chrono::high_resolution_clock::now();
		auto elapsed = std::chrono::duration_cast<std::chrono::nanoseconds>(end - begin);

		int error = sf_close(file_sf);

		printf("%.5f milliseconds\n", elapsed.count() * 1e-6);
		remove("test.wav");

	}

	return 0;
}
```

**Comment by evpobr** [comment]
> Experimenting further, I noticed that performance difference is **much more** significant (>10x slower) when the data to be written is initialized to non-zero values. Here are the mean values I am observing:

Yes, i can confirm that. IMHO this slowdown is not related to version. I've tested 1.0.30 build form MSYS2 (MinGW64) and results are similar to official 1.0.28 release.

**Comment by evpobr** [comment]
One more interesting thing. With lesser buffer size:

```c
#define	SF_BUFFER_LEN			(8192)

const size_t frameSize = SF_BUFFER_LEN / sizeof (double);
```

everything is MUCH faster.

**Comment by evpobr** [comment]
Replacing this:

```c
int k;
for (k = 0; k < frameSize; k++)
{
	data[k] = 0.5;
}
```

with:

```c
double data[frameSize] = { 0.5 };
```

makes everything even more faster :smile: And no difference between 0.0 and 0.5 anymore.

**Comment by krisfed** [comment]
Thank you, that is very useful to know that when built with MinGW64, 1.0.30 has the same performance as 1.0.28! 

For `double data[frameSize] = { 0.5 };`, wouldn't that only make the first element 0.5, and the rest would still be 0? In any case, this is just me trying to find simplified reproduction steps representative of our complete workflows (in which we see 150-200% regression overall when writing WAV files, and the data is not initialized with a for-loop). I did notice that if I include clipping and scaling commands, the regression is better (4000-5000ms, instead of >10,000ms for the above example):

```
sf_command(file_sf, SFC_SET_SCALE_INT_FLOAT_WRITE, NULL, SF_TRUE);
sf_command(file_sf, SFC_SET_CLIPPING, NULL, SF_TRUE);
```

**Comment by evpobr** [comment]
It seems like `lrint` is slow:

> The lrint family of functions provided by the C standard library should do what you want, and in fact compile to straightforward cvt* instructions on some other compilers, but are extremely sub-optimal on Microsoft's compiler. They are never inlined, so you always pay the cost of a function call. Plus, the code inside of the function is sub-optimal. Both of these have been reported as bugs, but we are still awaiting a fix. There are similar problems with other conversion functions provided by the standard library, including lround and friends.

**Comment by evpobr** [comment]
With this:

```c
#include <intrin.h>

static inline int psf_lrint (double const x) {
 return _mm_cvtsd_si32(_mm_load_sd(&x));
}

static void
d2les_array (const double *src, short *dest, int count, int normalize)
{	unsigned char	*ucptr ;
	short			value ;
	double			normfact ;

	normfact = normalize ? (1.0 * 0x7FFF) : 1.0 ;
	ucptr = ((unsigned char*) dest) + 2 * count ;

	while (--count >= 0)
	{	ucptr -= 2 ;
		value = psf_lrint (src [count] * normfact) ;
		ucptr [0] = value ;
		ucptr [1] = value >> 8 ;
		} ;
} /* d2les_array */
```

your benchmark with 1.0.30 shows results even beter than 1.0.28.

**Comment by evpobr** [comment]
@krisfed, check #663 please.

**Comment by krisfed** [comment]
@evpobr thank you very much for working on this! I was able to confirm that this change addresses the performance regression in our complete WAV-writing workflows.
