### ISSUE TITLE
Missing dither command documentation.

### ISSUE THREAD

**Issue by SmiVan** [libsndfile/libsndfile#674]
There are is no documentation in neither [the command documentation](https://github.com/libsndfile/libsndfile/blob/master/docs/command.md) nor [the header file](https://github.com/libsndfile/libsndfile/blob/master/include/sndfile.h.in) for the following commands:

- SFC_SET_DITHER_ON_WRITE
- SFC_SET_DITHER_ON_READ
- SFC_GET_DITHER_INFO_COUNT
- SFC_GET_DITHER_INFO

---

This is extra strange given these lines:
https://github.com/libsndfile/libsndfile/blob/bf15a91fb0a34baf01c942a3ef5dee5fc418660d/include/sndfile.h.in#L387-L391

**Comment by SmiVan** [comment]
I've thought that perhaps the documentation got deleted by accident, and checked the git history of sndfile.h.in and the web archive for http://www.mega-nerd.com/libsndfile/command.html up to 2004 - but it appears that there never was any documentation.

**Comment by erikd** [comment]
The API was designed, but dIthering was never implemented.

**Comment by SmiVan** [comment]
It would be good to annotate parts of sndfile.h which are reserved for future implementation such as this.

**Comment by evpobr** [comment]
@SmiVan , pull request?
