### ISSUE TITLE
How to build dylib on macOS for new ARM-based Apple Silicon macs

### ISSUE THREAD

**Issue by KoenTanghe** [libsndfile/libsndfile#678]
Does anyone know how I should build the dylib for the new Apple Silicon (ARM) macs, from an Intel mac?

I used to build a universal binary containing the 32-bit and 64-bit version using:
```
./configure CXXFLAGS="-march=i386 -m32 -mmacosx-version-min=10.5" CFLAGS="-march=i386 -m32 -mmacosx-version-min=10.5" --disable-external-libs
make -j4
cp src/.libs/libsndfile.1.dylib libsndfile-i386.1.dylib

make clean

./configure CXXFLAGS="-mmacosx-version-min=10.5" CFLAGS="-mmacosx-version-min=10.5" --disable-static --disable-external-libs
make -j4
cp src/.libs/libsndfile.1.dylib libsndfile-x64.1.dylib

lipo libsndfile-i386.1.dylib libsndfile-x64.1.dylib -create -output libsndfile.dylib
install_name_tool -id @rpath/libsndfile.dylib libsndfile.dylib
```

So, I thought that using the following would build the dylib for arm64-based new Silicon macs:
```
./configure CXXFLAGS="-march=arm64 -mmacosx-version-min=10.9" CFLAGS="-march=arm64 -mmacosx-version-min=10.9" --disable-external-libs
make -j4
```
but I'm getting this error:
```
...
checking whether the C compiler works... no
configure: error: in `/Users/ktanghe/Desktop/libsndfile/libsndfile-1.0.30':
configure: error: C compiler cannot create executables
```
(Note: this is the same error I get when I try to build the 32-bit version currently, but that is expected, as the latest XCode tools don't support building for 32-bit any longer.)

--> Has anyone succeeded building libsndfile for the new Apple Silicon macs? And if so, how?

Thanks,
Koen

**Comment by alexey-lysiuk** [comment]
I suggest to use CMake instead of `configure` script:
```
cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DBUILD_SHARED_LIBS=ON .
```
Although, if you really want to go old school way, it would be something like this:
```
./configure --host=aarch64-apple-darwin CFLAGS="-arch arm64"
```
Have no idea what the point of 10.9 deployment target for ARM Macs that run macOS 11.x only.

**Comment by KoenTanghe** [comment]
Thank you Alexey, using CMake worked fine indeed.

I also tried the "old school" way with the suggestion you made, but kept getting the same error I mentioned, so I went the CMake way.

Using deployment target 10.9 for the ARM build indeed doesn't make sense (my library should still work for Intel-based macOS 10.9, so I had added that, but I shouldn't do that for the ARM build).

In the end, I used this to make the build (no longer including the 32-bit version, only 64-bit Intel and ARM):

```
mkdir libsndfile
cd libsndfile
curl -L https://github.com/libsndfile/libsndfile/releases/download/v1.0.30/libsndfile-1.0.30.tar.bz2 --output libsndfile-1.0.30.tar.bz
tar xfvz libsndfile-1.0.30.tar.bz
cd libsndfile-1.0.30

cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DBUILD_SHARED_LIBS=ON .
cmake --build .
cp libsndfile.1.0.30.dylib ../libsndfile-x64.dylib

cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DBUILD_SHARED_LIBS=ON .
cmake --build .
cp libsndfile.1.0.30.dylib ../libsndfile-arm64.dylib

cd ..
lipo libsndfile-x64.dylib libsndfile-arm64.dylib -create -output libsndfile.dylib
install_name_tool -id @rpath/libsndfile.dylib libsndfile.dylib

otool -vf libsndfile.dylib
```

**Comment by KoenTanghe** [comment]
I'm closing the issue, as it is solved now.
