### ISSUE TITLE
Static and shared libraries should not be mutually exclusive.

### ISSUE THREAD

**Issue by riggs-** [libsndfile/libsndfile#684]
It would be very helpful to be able to run build time tests (i.e. BUILD_TESTING=ON) and still build shared libraries. Currently the cmake build files prevent us from having both. Could this be changed? (My cmake knowledge is somewhat limited, so I did not see a quick way to accomplish this.)

Background: When building packages on FreeBSD, we default to running build time tests whenever possible. But the resulting package should contain the shared libs for the consumers, obviously.

**Comment by evpobr** [comment]
Sorry, it is impossible at this moment. Our tests use private symbols that are not available from the shared library.

You can try Autools build system if it really need it. I looks like Autotools can build shared library and run tests at once. But I strongly suspect that it always builds both a shared and static library and runs tests with the static library.

If you want the same thing with CMake, run tests with static linking, and if everything went well, build a release with a shared library.
