### ISSUE TITLE
Release 1.0.31

### ISSUE THREAD

**Issue by evpobr** [libsndfile/libsndfile#692]
@SoapGentoo , @arthurt , @erikd , i guees it is time for minor release with @SoapGentoo as releaser.

@SoapGentoo , i've updated NEWS with latest changes. I recommend to choose a date convenient for you and assign it to 1.0.31 milestone. Next week or two will be fine as I think.

Hope the next release will be 1.1.0.

**Comment by evpobr** [comment]
@umlaeute

**Comment by SoapGentoo** [comment]
sounds good, let me prepare a PR for bumping the version and removing the auto-computed libtool versioning that has caused issues in libsamplerate (and would cause the same issue again once we release 1.1.0)

**Comment by evpobr** [comment]
You better to make release commit to master branch directly. GitHub rewrites commits on merge, you will loose your signature IMHO.

I found it convenient to make a separate release commit, in which I bumped the versions and updated the news if needed. Very nice and clear. Here is my latest release commit: 68958f9.

**Comment by SoapGentoo** [comment]
everything done from my side

**Comment by evpobr** [comment]
@SoapGentoo ,  Windows binaries:

[libsndfile-1.0.31-win64.zip](https://github.com/libsndfile/libsndfile/files/5862418/libsndfile-1.0.31-win64.zip)
[libsndfile-1.0.31-win32.zip](https://github.com/libsndfile/libsndfile/files/5862414/libsndfile-1.0.31-win32.zip)

**Comment by SoapGentoo** [comment]
Thanks, added, and we're done here.
