### ISSUE TITLE
release-text: turn warning about missing bootstrap into notification

### ISSUE THREAD

**Issue by umlaeute** [libsndfile/libsndfile#695]
the [Release page for 1.0.31](https://github.com/libsndfile/libsndfile/releases/tag/1.0.31) has a big fat warning:

> **Do not use the "Source code (zip)" or "Source code (tar.gz)" links, as these do not include the necessary bootstrapped files.**

in the light of https://github.com/libsndfile/libsamplerate/pull/145#issuecomment-766371835, I'm wondering what the purpose of this warning is.

That is:
- Is this mainly a **convenience warning**, so you don't get "doesn't work" complaints from people who cannot be bothered to run `autoreconf` themselves?
- or is building from non-bootstrapped sources (as generated by `git archive`) **not "supported"**, as the release process includes non-trivial mangling of the sources to generate the "release tarball"? (I consider running `autoreconf`,`cmake` or siimilar to be a "trivial" mangling in this context).

if it is the latter, then you probably should just make sure that the auto-generated source tarballs are useless (I know projects that do that, altough I'm personally not very happy about this).

If it is the former, then i think you should turn the **Do not use...** warning into a less-committal **If you use...** (including a short explanation on what needs to be done).
I would even suggest to add this information to the `README.md` (*instead* of the release notes), as it applies both to `git clone`s and the autogenerated source tarball.s

**Comment by evpobr** [comment]
@SoapGentoo ? It makes sense IMHO.

**Comment by SoapGentoo** [comment]
This is mainly about the former. Using a `git archive` tarball + `autoreconf` is perfectly "supported", except most people don't want to actually bootstrap the autotools (if they even know what they are). Please suggest the exact wording, because this seems to matter more to you.

**Comment by evpobr** [comment]
It seems to me that this phrase will not be clear to CMake users.

**Comment by umlaeute** [comment]
so what is the suggested phrase for CMake users?

i could prepare a PR for an updated README, if that is what you want (though i haven't looked at the CMake state-of-affairs)

**Comment by SoapGentoo** [comment]
You suggested changing the wording on the releases page? I wouldn't know what to change in the README

**Comment by umlaeute** [comment]
> You suggested changing the wording on the releases page? I wouldn't know what to change in the README

and [I said](https://github.com/libsndfile/libsndfile/issues/695#issue-796663595):
> I would even suggest to add this information to the README.md (instead of the release notes), as it applies both to git clones and the autogenerated source tarball.s

**Comment by evpobr** [comment]
@umlaeute , 

> so what is the suggested phrase for CMake users?

CMake users can use all these archives and git checkout without any problems at all. For them, this warning is useless at all.

> i could prepare a PR for an updated README, if that is what you want (though i haven't looked at the CMake state-of-affairs)

Let's take a look.

**Comment by umlaeute** [comment]
actually, i just checked the [`README.md`](https://github.com/libsndfile/libsndfile/blob/251a435566bd798a45629425f3a61df8d61e3ba1/README.md) and it obviously states that the entire autotools chain is a requirement and that one must run `./autogen.sh` before running `./configure`:

https://github.com/libsndfile/libsndfile/blob/251a435566bd798a45629425f3a61df8d61e3ba1/README.md#L35

https://github.com/libsndfile/libsndfile/blob/251a435566bd798a45629425f3a61df8d61e3ba1/README.md#L43

https://github.com/libsndfile/libsndfile/blob/251a435566bd798a45629425f3a61df8d61e3ba1/README.md#L48-L49


so there isn't really much to *add* here.

OTOH, the (old, plain-text) `README`(https://github.com/libsndfile/libsndfile/blob/251a435566bd798a45629425f3a61df8d61e3ba1/README) do not mention it.

However, I think that having both `README` and `README.md` is a problem per se, as it is unclear which one is the canonical one (given that both are *almost* identical).
i think, you should get rid of one (just make sure to not break the autotools build system while doing so).

---

so I'd go for the following rephrasing in the release notes:

> Please note that the "Source code (zip)" or "Source code (tar.gz)" downloads require you to have the autotools toolchain (`autoconf`, `autogen`, `automake` and `libtool`) installed. If you don't want to install it (or don't know what this means), you should probably download the `libsndfile-*.tar.bz2` asset instead.

**Comment by evpobr** [comment]
> actually, i just checked the [`README.md`](https://github.com/libsndfile/libsndfile/blob/251a435566bd798a45629425f3a61df8d61e3ba1/README.md) and it obviously states that the entire autotools chain is a requirement and that one must run `./autogen.sh` before running `./configure`:
> 
> https://github.com/libsndfile/libsndfile/blob/251a435566bd798a45629425f3a61df8d61e3ba1/README.md#L35
> 
> https://github.com/libsndfile/libsndfile/blob/251a435566bd798a45629425f3a61df8d61e3ba1/README.md#L43
> 
> https://github.com/libsndfile/libsndfile/blob/251a435566bd798a45629425f3a61df8d61e3ba1/README.md#L48-L49
> 
> so there isn't really much to _add_ here.
> 
> OTOH, the (old, plain-text) `README`(https://github.com/libsndfile/libsndfile/blob/251a435566bd798a4
> so I'd go for the following rephrasing in the release notes:
> 
> > Please note that the "Source code (zip)" or "Source code (tar.gz)" downloads require you to have the autotools toolchain (`autoconf`, `autogen`, `automake` and `libtool`) installed. If you don't want to install it (or don't know what this means), you should probably download the `libsndfile-*.tar.bz2` asset instead.

And add before: Note for Autotools users.

**Comment by evpobr** [comment]
TODO: remove plain README.

**Comment by SoapGentoo** [comment]
I've changed the text on the release page.

**Comment by evpobr** [comment]
Good. @umlaeute ?

**Comment by umlaeute** [comment]
@evpobr yes thanks.

for the future, you might still incorporate something along this text into the `README.md` and reference this from the release notes (it seems quite a lot of boilerplate that is repeated for each and every release)
