### ISSUE TITLE
Package should lie about its macOS compatibility version like original upstream did

### ISSUE THREAD

**Issue by kode54** [libsndfile/libsndfile#742]
Upstream libsndfile from mega-nerd.com's last version before discontinuing, 1.0.28, reported a "compatibility version" of 2.0.0, while this package reports 1.0.0. This makes it look like a downgrade. Should this be fixed, or should everyone be told either "recompile everything, old upstream was a bad liar" or simply "keep using the discontinued and broken version forever more".

**Comment by evpobr** [comment]
Hi @kode54 , thanks for issue. It is bug and i'm working on fix.

**Comment by SoapGentoo** [comment]
The next version will fix this. Importantly, don't use the CMake-based buildsystem on macOS, use Autotools instead.

**Comment by kode54** [comment]
I chose to use CMake because an autotools based script would have required autogen, and MacPorts doesn't support building autogen for +universal, and building a universal package somehow requires that dependency to be universal.

**Comment by SoapGentoo** [comment]
why dont you use our pre-bootstrapped tarballs? There's no need to run autogen yourself?

**Comment by kode54** [comment]
I wasn't aware the tarballs on the release page were pre-bootstrapped. I'll let someone else take care of that.

**Comment by thesamesam** [comment]
@kode54 I think users might appreciate it if someone could get around to doing it sooner rather than later (to reduce the damage).
