### ISSUE TITLE
Problem with no sound in a game

### ISSUE THREAD

**Issue by jam-85** [libsndfile/libsndfile#744]
not sure if this is relevent here but im having an issue with 1 steam game that used to work fine, now theres no audio.

refined the error down to:

ALSA lib dlmisc.c:339:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/usr/lib/libsndfile.so.1: undefined symbol: ogg_stream_pageout_fill)
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such device or address

im using manjaro cinnamon, current libsndfile is 1.0.31. (no sound from game)
i replaced libsndfile with version 1.0.28 and re-linked it the sound works fine, but breaks the rest of the system sound.
is this a issue with the devs of the steam game or is this a bug?

im new to github (as a registered user) so forgive me for any formatting issues.

**Comment by evpobr** [comment]
Hi @jam-85 . I'm pretty sure you need to open this issue in Majaro bugtracker.

**Comment by jam-85** [comment]
hi ok thanks
