### ISSUE TITLE
Overflow in mpeg_l3_encoder_construct()

### ISSUE THREAD

**Issue by evpobr** [libsndfile/libsndfile#756]
@arthurt , is it important?

    [proc] Executing command: c:\msys64\mingw64\bin\cmake.exe --build c:/msys64/home/evpobr/libsndfile/build --config Release --target all -j 6 --
    [build] [1/2  50% :: 0.999] Building C object CMakeFiles/sndfile.dir/src/mpeg_l3_encode.c.obj
    [build] ../src/mpeg_l3_encode.c: In function 'mpeg_l3_encoder_construct':
    [build] ../src/mpeg_l3_encode.c:429:24: warning: overflow in conversion from 'int' to 'signed char:1' changes value from '1' to '-1' [-Woverflow]
    [build]   429 |   pmpeg->initialized = SF_TRUE ;
    [build]       |                        ^~~~~~~
    [build] [2/2 100% :: 2.442] Linking C shared library libsndfile.dll
    [build] Build finished with exit code 0

**Comment by arthurt** [comment]
Not important, but annoying.

To fixes. At mpeg_l3_encode.c:45, change to unsigned int, or remove the C99 bit field `:1`, as it isn't saving any space or making anything faster anyways.
