### ISSUE TITLE
Digit exceeds base in src/version-metadata.rc

### ISSUE THREAD

**Issue by naabtog** [libsndfile/libsndfile#758]
Since commit `dfdad63` I'm having error while making a cross-compilation. It goes like this:
```
  CC       src/ALAC/matrix_enc.lo
  CC       src/ALAC/alac_decoder.lo
  CC       src/ALAC/alac_encoder.lo
/bin/bash ./libtool   --tag=RC --mode=compile i686-w64-mingw32-windres  src/version-metadata.rc -o src/version-metadata.lo
/usr/bin/python ./src/create_symbols_file.py os2 1.0.32 > ./src/Symbols.os2
/usr/bin/python ./src/create_symbols_file.py static 1.0.32 > ./src/Symbols.static
  CCLD     src/GSM610/libgsm.la
libtool: compile:  i686-w64-mingw32-windres src/version-metadata.rc -o src/version-metadata.o
src/version-metadata.rc:5: digit exceeds base
i686-w64-mingw32-windres: src/version-metadata.rc:5: syntax error
make[2]: *** [Makefile:4202: src/version-metadata.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/user/ffmpeg-windows-build-helpers/sandbox/win32/libsndfile_git'
make[1]: *** [Makefile:3265: all-recursive] Error 1
make[1]: Leaving directory '/home/user/ffmpeg-windows-build-helpers/sandbox/win32/libsndfile_git'
make: *** [Makefile:1524: all] Error 2
```
and stops. When I manually reverted changes made in commit `dfdad63`, everything compiled fine. Ubuntu 20.04.2 LTS x64

**Comment by evpobr** [comment]
@naabtog , thanks for report.

I cannot reproduce it on Windows 7 + MinGW.

**Comment by evpobr** [comment]
Can you make clean rebuild?

**Comment by evpobr** [comment]
Send generated version-metadata.rc please.

**Comment by naabtog** [comment]
@evpobr here's the [file](https://drive.google.com/file/d/1Ijnp8vEWbiTjMcr2ip_s00xBhWALDyvi/view?usp=sharing).
```
#include <windows.h>

LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_AUS
1 VERSIONINFO
	FILEVERSION		1,1,0beta1,0
	PRODUCTVERSION	1,1,0beta1,0
	FILEOS			VOS__WINDOWS32
	FILETYPE		VFT_DLL
	FILESUBTYPE		VFT2_UNKNOWN
	FILEFLAGSMASK	0x00000000
	FILEFLAGS		0x00000000
{
	BLOCK "StringFileInfo"
	{
		BLOCK "040904e4"
		{
			VALUE "FileDescription", "A library for reading and writing audio files."
			VALUE "FileVersion", ".0\0"
			VALUE "Full Version", "1.1.0beta1"
			VALUE "InternalName", "libsndfile"
			VALUE "LegalCopyright", "Copyright (C) 1999-2012, Licensed LGPL"
			VALUE "ProductName", "libsndfile-1 DLL"
			VALUE "ProductVersion", ".0\0"
			VALUE "Language", "Language Neutral"
		}
	}
	BLOCK "VarFileInfo"
	{
		VALUE "Translation", 0x0409, 0x04E4
	}
}
```

**Comment by evpobr** [comment]
@SoapGentoo , @arthurt any ideas how to adopt it?

```
WIN_RC_VERSION=`echo $PACKAGE_VERSION | $SED -e "s/p.*//" -e "s/\./,/g"`
```

And how the hell did it work before, [here](https://github.com/libsndfile/libsndfile/commit/5afbcc6cf44fe3a9dcf8e11169f444c873e58bf6) for example?

Or would it be better to hardcode them like we did with `abi_version`?

**Comment by arthurt** [comment]
Ahhhh, ha ha ha, this explains a lot. It would seem Erik's naming for pre-releases was 'preX'.

The sed script has two expressions that both execute on the line. The second expression `s/\./,/g` replaces periods with commas, makes sense.

The first expressions `s/p.*//` truncates the version string to everything before a 'p'. So, for the example you linked, '1.0.28pre1' would go out as '1,0,28'.

How that generated '.0\0' I have no idea. Note that cmake can also generate WIN_RC_VERSION.

In the case of the sed statement, if we want to keep using the 'beta' suffix, a fix would be to change the first expression to `s/beta.*//`, or allow for either (because, I dunno, reasons) `s/\(pre\|beta\).*//`, or to be really verbose:
```
sed -e 's/pre.*//' -e 's/beta.*//' -e 's/\./,/g'
```
Would also work.

**Comment by arthurt** [comment]
Or, to be completely suffix-agnostic

```
sed -Ee 's/^([0-9]+)\.([0-9]+)\.([0-9]+).*/\1,\2,\3/' 
```
