### ISSUE TITLE
Encoding into ogg in Windows.

### ISSUE THREAD

**Issue by fredvs** [libsndfile/libsndfile#761]
Hello.

In Linux I use libsndfile to encode into ogg the input of a audio card.

It works perfectly, for _sf_write_short_, _sf_write_int_ and _sf_write_float_.
The ogg file produced is recognized by every tenor players.

But for Windows, with the same code, each _sf_write_xxx_ return 0 and the resulted if a file of 46 octets not readable.

Is _sf_write_xxx_ and ogg encoder working on Windows?

Thanks.

Fre;D

**Comment by evpobr** [comment]
Hi @fredvs .

We need more info.

1. Do you use Ogg Vorbis or Ogg Opus?
2. Version of libsndfile you use.
3. We need test file to confirm bug.

**Comment by fredvs** [comment]
Hello @evpobr 

Ho, I am totally sorry, it was a stupid mistake from me with directory separator (/ vs \).
All is working perfectly on Windows too, have a perfect day.

Fre;D

**Comment by evpobr** [comment]
It's good :smile:
