### ISSUE TITLE
Public constant values clash

### ISSUE THREAD

**Issue by evpobr** [libsndfile/libsndfile#766]
https://github.com/libsndfile/libsndfile/blob/86c9f9eb7022d186ad4d0689487e7d4f04ce2b29/include/sndfile.h.in#L223-L227

@arthurt , is it mistake?

**Comment by arthurt** [comment]
Yeah, that would be because of two pull requests each adding new commands independently, then doing a merge that succeeds, but creates the two consts with the same value.

I guess bump the bitrate ones up, I know they haven't been released.

**Comment by evpobr** [comment]
Agree. PR?

**Comment by evpobr** [comment]
Ok, i will create it.
