### ISSUE TITLE
MP3 support (ENABLE_MPEG=ON)

### ISSUE THREAD

**Issue by xtingray** [libsndfile/libsndfile#777]
Hi,
I compiled the libsndfile source code enabling the MPEG support, hoping to read MP3 files. As part of the cmake configuration output I got this lines:
-- The following features have been enabled:
   ENABLE_MPEG, enable MPEG audio (including mp3) codecs

But when I try to load an MP3 file using this instruction, it always fails:
`    SNDFILE *sndFile = sf_open(soundFilePath, SFM_READ, &soundInfo);`

Am I doing something wrong or the MP3 support is just not implemented yet? Thank you for any hint.

**Comment by evpobr** [comment]
Hi @xtingray . 

Need more info: OS, version of libsndfile, required libraries installed (for MP3 - lame and libmpg123.

**Comment by xtingray** [comment]
This is the environment I am using to run my tests:
OS: Ubuntu 21.04 (x86_64)
C Compiler: GCC version 10.3.0

Here is the CMake log:
https://tupitube.com/tmp/cmake_config.log
And here is the compilation log:
https://tupitube.com/tmp/compilation.log

Note:  It seems I got the dependencies required:
-- Found Lame: /usr/lib/x86_64-linux-gnu/libmp3lame.so  
-- Found Mpg123: /usr/lib/x86_64-linux-gnu/libmpg123.so (found suitable version "1.26.4", minimum required is "1.25.10")

**Comment by evpobr** [comment]
> version of libsndfile

**Comment by xtingray** [comment]
To get the source code, I ran this command (master branch):
git clone https://github.com/libsndfile/libsndfile.git

The README file says: This is libsndfile, 1.0.29

**Comment by evpobr** [comment]
> The README file says: This is libsndfile, 1.0.29

Oops, we forgot to update README.

**Comment by evpobr** [comment]
Run `sndfile-info` from your build directory and paste output.

**Comment by xtingray** [comment]
Command without parameters:
```
./sndfile-info 
Usage :
  sndfile-info <file> ...
    Prints out information about one or more sound files.
  sndfile-info --instrument <file>
    Prints out the instrument data for the given file.
  sndfile-info --broadcast <file>
    Prints out the broadcast WAV info for the given file.
  sndfile-info --channel-map <file>
    Prints out the channel map for the given file.
  sndfile-info --cart <file>
    Prints out the cart chunk WAV info for the given file.

Using libsndfile-1.1.0beta1.
```

**Comment by xtingray** [comment]
Command with parameter:

```
./sndfile-info /tmp/test.mp3

File : /tmp/test.mp3
Length : 84534
Found 'ID3' marker.
  ID3v2.4 header length :	6222

MPEG-1/2 Audio

  MPEG version   : MPEG 1.0
  layer          : 3
  rate           : 48000
  mode           : joint stereo
  mode ext       : 0
  framesize      : 576
  crc            : 0
  copyright flag : 0
  private flag   : 0
  original flag  : 1
  emphasis       : 0
  bitrate mode   : variable
ID3v2 Tags
  TSSE        : Lavf57.83.100


Sample Rate : 48000
Frames      : 394031
Channels    : 2
Format      : 0x00230082
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:08.209
Signal Max  : 7803.12 (-12.46 dB)
```

**Comment by evpobr** [comment]
It seems like your libsndfile build has MP3 support. Probably something wrong with your code. Check `sndfile-info` source in `programs/` or examples in `examples`. Also check error message after `sf_open` call:

http://libsndfile.github.io/libsndfile/api.html#error

**Comment by xtingray** [comment]
Command with parameter:

```
./sndfile-info /tmp/test.mp3

File : /tmp/test.mp3
Length : 84534
Found 'ID3' marker.
  ID3v2.4 header length :	6222

MPEG-1/2 Audio

  MPEG version   : MPEG 1.0
  layer          : 3
  rate           : 48000
  mode           : joint stereo
  mode ext       : 0
  framesize      : 576
  crc            : 0
  copyright flag : 0
  private flag   : 0
  original flag  : 1
  emphasis       : 0
  bitrate mode   : variable
ID3v2 Tags
  TSSE        : Lavf57.83.100


Sample Rate : 48000
Frames      : 394031
Channels    : 2
Format      : 0x00230082
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:08.209
Signal Max  : 7803.12 (-12.46 dB)
```

**Comment by xtingray** [comment]
Finally, I found the cause of the problem. I have to include the libsndfile library path as part of the LD_LIBRARY_PATH variable before launching my app:

`export LD_LIBRARY_PATH="/usr/local/libsndfile/lib"`

Now it works perfectly. Thank you so much for your help and for this great project!

**Comment by evpobr** [comment]
You're welcome!
