### ISSUE TITLE
opus: how much difference is expected after writing and reading data back?

### ISSUE THREAD

**Issue by krisfed** [libsndfile/libsndfile#788]
Hi all,

We are using libsndfile ~~1.0.29~~ 1.0.30, and just starting to use the opus functionality (yay!). We noticed that there are some significant differences between data were are trying to write and the data we read back. The absolute differences for individual values can be as large as about 1.

I realize that **some** differences are to be expected after data goes through encoding and decoding. But unfortunately I am not an expert in audio in general, and in opus codec specifically, so I just **wanted to check if results like these are normal for opus**. My understanding is that the data range for opus is [-1, 1], so the absolute differences that are close to 1 in magnitude seem rather significant. But the audio sounds ok.

Here is an illustration with some simplified reproduction code. The data is randomly generated in the [-1, 1] range (and is attached as [data_original.txt](https://github.com/libsndfile/libsndfile/files/7470685/data_original.txt)), and the code is writing and reading back a single-channel opus file. (But we are observing similar results with real audio data and 2 channels.)

```
#include <iostream>
#include <fstream>

#include "sndfile.h"

int main()
{
    // read in original data from txt file
    int num = 2400;
    double originalData[num];
    
    std::ifstream originalDataFile;
    originalDataFile.open("data_original.txt");
    
    for (int i=0; i<num; i++){
        originalDataFile >> originalData[i];
    }
    originalDataFile.close();
    
    // write it to opus file
    SF_INFO sndFileInfo;
    sndFileInfo.samplerate = 48000;
    sndFileInfo.channels = 1;
    sndFileInfo.format = SF_FORMAT_OGG | SF_FORMAT_OPUS;
    
    SNDFILE* sndFile = sf_open("mytest.opus", SFM_WRITE, &sndFileInfo);

    double quality = 0.75;
    sf_command(sndFile, SFC_SET_VBR_ENCODING_QUALITY, &quality, sizeof(double));
    sf_command(sndFile, SFC_SET_SCALE_INT_FLOAT_WRITE, NULL, SF_TRUE);
    
    sf_count_t framesWritten = sf_writef_double(sndFile, originalData, num);
    std::cout << "Written " << framesWritten << " frames." << std::endl;
    
    int error = sf_close(sndFile);
    if (error != SF_ERR_NO_ERROR) {
        std::cout << "Error closing file for writing: " << error << std::endl;
    }
    
    // read it back
    SF_INFO sndFileInfoRead;
    SNDFILE* sndFileRead = sf_open("mytest.opus", SFM_READ, &sndFileInfoRead);
    sf_count_t startSample = 0;
    sf_count_t framesSeeked = sf_seek(sndFileRead, startSample, SEEK_SET);
    double readBackData[num];
    sf_count_t framesRead = sf_readf_double(sndFileRead, readBackData, num);
    std::cout << "Read back " << framesRead << " frames." << std::endl;

    error = sf_close(sndFileRead);
    if (error != SF_ERR_NO_ERROR) {
        std::cout << "Error closing file for writing: " << error << std::endl;
    }
    
    // write data from opus file to txt file
    std::ofstream resultDataFile("data_result.txt");
    
    for (int i=0; i<num; i++){
        resultDataFile << readBackData[i] << std::endl;
    }
    resultDataFile.close();
    
    
    return 0;
}
```
We are comparing the values in data_original.txt and data_result.txt.  For our default quality of 0.75, we are seeing absolute differences for up to 0.8:
![q75](https://user-images.githubusercontent.com/1648280/140193379-d92a3e69-68c0-4f3a-a098-b5c78a31d94d.png)
(read back data: [data_result_q75.txt](https://github.com/libsndfile/libsndfile/files/7470714/data_result_q75.txt)).

As seems reasonable, we are seeing larger differences (and "fatter" distribution of them) for low quality (0) vs high quality (1). But for low quality, data also seems to be scaled to a smaller range. For example, this is quality of 1:
![q100](https://user-images.githubusercontent.com/1648280/140194438-25a281b5-fc7a-4a29-85c6-e8b4f03c23bb.png)
([data_result_q100.txt](https://github.com/libsndfile/libsndfile/files/7470744/data_result_q100.txt))

compared to quality of 0:

![q0](https://user-images.githubusercontent.com/1648280/140194496-126e7bfa-74db-41a8-bed2-585789f4c3e4.png)
([data_result_q0.txt](https://github.com/libsndfile/libsndfile/files/7470746/data_result_q0.txt))

I would very much appreciate a sanity check on whether these results look like something expected or if they seem off. Thanks a lot!

**Comment by evpobr** [comment]
Hi @krisfed . We don't support previous patch releases. Please, check latest release, we have many bugs fixed since 1.0.29.

**Comment by krisfed** [comment]
Thank you for taking a look, @evpobr ! My apologies, we are actually using **1.0.30** (I was looking at the README file which still lists 1.0.29, even in the current master branch :( ). We are really looking forward to the official release of 1.1.0 which fixes the CVE https://github.com/libsndfile/libsndfile/issues/687 , and we are planning to upgrade to that ASAP once it is out.

I can try to see if I observe the same with 1.0.31, but I was hoping to get an idea if these results do look wrong.. Sounds like you think they might be due to a bug?

**Comment by krisfed** [comment]
I tried running the same repro code with 1.0.31, and I am getting the same results:

Quality 1
![q100_1 0 31](https://user-images.githubusercontent.com/1648280/140314472-b317c332-fc0e-44cc-ac46-f11c30844672.png)
[data_result_q100_1.0.31.txt](https://github.com/libsndfile/libsndfile/files/7474786/data_result_q100_1.0.31.txt)

Quality 0.75
![q75_1 0 31](https://user-images.githubusercontent.com/1648280/140315059-c3da3527-e926-4ad0-b585-6251b9517cb2.png)
[data_result_q75_1.0.31.txt](https://github.com/libsndfile/libsndfile/files/7474790/data_result_q75_1.0.31.txt)

Quality 0
![q0_1 0 31](https://user-images.githubusercontent.com/1648280/140315131-c06037fd-8f47-43f9-8590-dd739a44f300.png)
[data_result_q0_1.0.31.txt](https://github.com/libsndfile/libsndfile/files/7474793/data_result_q0_1.0.31.txt)

So do these differences look unexpected?

**Comment by evpobr** [comment]
@arthurt , can you help here?

**Comment by krisfed** [comment]
I am leaning more and more towards concluding that this is expected... The above are results for randomly generated data (which might be a worse-case scenario?). I have tried it on a sine wave, and seeing much more reasonable differences there:

![q75_sine](https://user-images.githubusercontent.com/1648280/140998116-39588aaf-a361-4351-896b-5f1e37eeb453.png)

But I would really appreciate a confirmation from somebody more knowledgeable about opus codec.

**Comment by arthurt** [comment]
First, wow, thanks for the impressive tests!

I can't really answer if that is correct or not. libsndfile doesn't contain any Opus codec code, but uses the encoder and decoder from `libopus`, the reference implementation from Xiph.Org.

Bugs that libsndfile could introduce into the output data would be if the samples are offset (bad granule position, codec delay), seeking doesn't work or isn't exact, and possibly amplitude issues.

To my mind, the results you present here make sense. Opus is a lossy codec and it is tuned to human-perception. (White noise still sounds like white noise :smiley:) It's actually a hybrid dual-codec, one tuned for general-human perceived fidelity, the other tuned for low-bandwidth-voice-perception.

To make very sure, you can try replicating your tests with the command `opusenc` which uses `libopusfile` and not libsndfile. `libopusfile` is a higher level library built on `libopus` and `libogg`. (Libsndfile does not use libopusfile, and uses libopus and libogg directly.)

I am aware in one decode output difference between libopusfile and libsndfile for opus files and that is that libopusfile always applies dithering and sample-rate conversion to it's output, (even if the output sample rate matches the file's) and somehow achieves a better signal-to-noise ratio for very small signals. I'm still not totally sure why. I fear a bug in libopus that the dithering/SRC in libopusfile hides, (but that might not even make sense,) or a bug with our floating-point-to-int conversion.

**Comment by arthurt** [comment]
Probably the best place to answer this would be at the official libopus project on GitLab: https://gitlab.xiph.org/xiph/opus

**Comment by krisfed** [comment]
Thank you, @arthurt , this makes a lot of sense! The detailed response is much appreciated :)
