### ISSUE TITLE
How to compile libsndfile on Windows?

### ISSUE THREAD

**Issue by xtingray** [libsndfile/libsndfile#804]
Hi,
I would like to compile the **libsndfile** source files on Windows using **MinGW/cmake** from the console. I was looking for some detailed manual or something on Google but I couldn't find anything handy. 

Is this possible? I appreciate any advice/recommendation. Thanks!

**Comment by evpobr** [comment]
Hi @xtingray . I hope you have already succeeded. If not, read the README.md for a lot of advice. If we talk about MinGW, I successfully built our library on this platform.

**Comment by xtingray** [comment]
Following my research, finally I could call libsound code from my own project doing this little trick:
1. I copied the file sndfile.h from my Linux system to my Windows box
2. I downloaded and installed the libsndfile package for Windows: http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28-w64-setup.exe. From the installation path I copied the file libsndfile-1.dll

Using those files to compile my own source code I was able to create a binary successfully. My only problem now is that the DLL I used doesn't have support for MP3 files. On Linux I have the problem solve, but on Windows using MinGW currently I am stuck.

**Comment by xtingray** [comment]
@evpobr Were you able to include MP3 support on your Windows build? I was checking the documentation but I only saw references to MS Visual Studio, so I am a little lost. I appreciate any hint.

**Comment by evpobr** [comment]
To begin with, explain whether it is essential to build using MinGW?

**Comment by xtingray** [comment]
Just a little of context: I am the developer of an open source project called "TupiTube Desk", it is an animation software focused on kids and teenagers. Currently, I deliver installers of this tool for Windows, Mac and Linux. My development environment is based on MinGW in all the three platforms, working without any issue.
Recently, I added the libsndfile dependency as part of a lip-sync module I am working on, and it provides me great features for my project. I can compile and link the libraries on Mac and Linux using MinGW in a pretty clean way (even including the MP3 support). So, that's the reason I would like to try it using this compiler. I want to preserve my development standard. Besides, if I can compile libsndfile using MinGW on Linux and Mac, why it shouldn't be possible on Windows?   

Anyway, there are two possible options for me to find a solution for my problem:
1. To learn how to compile libsndfile on Windows using MinGW
2. To find the right libsndfile DLL files for Win32 and Win64 with MP3 support included
 
I appreciate any hint you can share with me in this matter. Thanks!

**Comment by evpobr** [comment]
Are you using this: [MSYS2](https://www.msys2.org/)?

**Comment by xtingray** [comment]
No. I use the MinGW compiler included in the Qt installer, as Qt is the development framework I use to develop TupiTube:
https://www.qt.io/download-open-source

**Comment by evpobr** [comment]
It is problem. Then you need to build all dependencies using make and your MinGW toolmain and install it somewhere e.g `c:\mingw`.

Then clone latest sources from this repo, and point CMake to that installed dependencies directory, probably `CMAKE_INSTALL_PREFIX` should work.

**Comment by evpobr** [comment]
In general, many difficulties await you.

> I am the developer of an open source project called "TupiTube Desk", it is an animation software focused on kids and teenagers.

Wow, that's cool.

**Comment by evpobr** [comment]
Yes, and also try Vcpkg, I think it supports MinGW. If so, then everything will be much simpler. Package managers are cool.

**Comment by xtingray** [comment]
Ok, taking advantage of your suggestions, I am exploring options. Here some notes:

1. I didn't remember that actually I was working with MSYS2? for some specific dependencies. Anyway, when I try to run the cmake command from the libsndfile folder I got this error message:
```CMake Error at CMakeLists.txt:39 (project):
  Running

   'nmake' '-?

  failed with:

   The system cannot find the file specified'```

Is there any option to set the C++ compiler to **MinGW**, including the "make" command as part of the tools? I guess there should be a clean way to do it, right?
I am aware that  dealing with compilation dependencies will be a hell, but I want to try it using **MSYS2** as my package manager, facing one problem at a time.

2. I found this interesting repository: https://github.com/bastibe/libsndfile-binaries
I had no idea you could create DLL files from Unix systems using a tool called **MXE**. I tried to follow the procedure but the documentation is poor and imprecise. Just out of curiosity, have you experience trying to use this tool?

3. As you mentioned in a previous comment, you could compile libsndfile using Visual Studio. I would like to know if you could enable the MP3 support in your DLL files. Could you?

Thank you for your patience and support.

**Comment by evpobr** [comment]
> 1. I didn't remember that actually I was working with MSYS2? for some specific dependencies. Anyway, when I try to run the cmake command from the libsndfile folder I got this error message:

https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html



> 2\. I found this interesting repository: https://github.com/bastibe/libsndfile-binaries
>     I had no idea you could create DLL files from Unix systems using a tool called MXE. I tried to follow the procedure but the documentation is poor and imprecise. Just out of curiosity, have you experience trying to use this tool?

I've heard of it, but I've never used it. For today it is outdated, I think so.

> 3\. As you mentioned in a previous comment, you could compile libsndfile using Visual Studio. I would like to know if you could enable the MP3 support in your DLL files. Could you?

Okay, especially for you:

[libsndfile-1.1.0beta2-win32-77acc6d.zip](https://github.com/libsndfile/libsndfile/files/7876398/libsndfile-1.1.0beta2-win32-77acc6d.zip)
[libsndfile-1.1.0beta2-win64-77acc6d.zip](https://github.com/libsndfile/libsndfile/files/7876399/libsndfile-1.1.0beta2-win64-77acc6d.zip)

**Comment by evpobr** [comment]
> 1. Anyway, when I try to run the cmake command from the libsndfile folder I got this error message:
> 
> CMake Error at CMakeLists.txt:39 (project): Running nmake -? failed with: The system cannot find the file specified

By the way, if you use Qt Creator, is it worth opening and collecting libsndfile and dependencies in it? Usually, the IDE correctly configures the CMake environment to work.

**Comment by xtingray** [comment]
@evpobr I want to thank you for your support and collaboration. From now, libsndfile will be an official dependency for TupiTube Desk. I tested the libraries you sent me and the compilation of my source code worked like a charm. 
Here is a screenshot of the lip-sync coming feature that uses the libsndfile resources:  

![libsndfile](https://user-images.githubusercontent.com/2789669/149846712-41f7f3ad-f435-4c88-b013-fafbffd51ee6.png)
Checking our usage statistics, just last December more than 4000 children from many places around the world used our software, so I want you to know that from now, your project indirectly supports our mission. Thank you!

![india](https://user-images.githubusercontent.com/2789669/149847998-8d1425c8-5ea4-42cc-93c6-407dc5ebbd15.jpg)

**Comment by evpobr** [comment]
Glad to help. But I want to note that a lot of people contributed to this project, and I'm not even the author :-)
