### ISSUE TITLE
building for android with AndroidStudio and CMake

### ISSUE THREAD

**Issue by scar20** [libsndfile/libsndfile#808]
Hi,
It would be nice to have a built for android. I'm on Windows with only AndroidStudio for coding just to say that I'm not fluent with build tools. Fortunately, I could find a sample app https://github.com/sheraz-nadeem/oboe_recorder_sample that use libsndfile and I've been able to duplicate it, build it and add my own method to get a short buffer from libsndfile. It build libsndfile 1.0.29 as a static lib included in a shared lib referred by the app.

Now, I tried to rebuild with the latest version of libsndfile to benefit all the hard work (and thanks a lot for this) to integrate mp3 support. This time it fail. From the entry point CMakeList.txt, I adapted include_directory to reflect the new structure of the distribution, from:
```
### ADD LIBSNDFILE LIBRARY
set(LIB_SND_FILE_DIR ../../../../libsndfile)
add_subdirectory(${LIB_SND_FILE_DIR} ./sndfile)
include_directories(${LIB_SND_FILE_DIR}/src)
```
to:
```
### ADD LIBSNDFILE LIBRARY
set(LIB_SND_FILE_DIR ../../../../libsndfile)
add_subdirectory(${LIB_SND_FILE_DIR} ./sndfile)
include_directories(${LIB_SND_FILE_DIR}/include)
```
It fail at:
`ninja: error: 'C:/Users/Sylvain/AndroidStudioProjects/libsndfileProjects/SndFileLib2/libsndfile/cmake/sqlite/CMakeAutoGenScript.cmake', needed by 'sndfile/tests/utils.c', missing and no known rule to make it`
I tried naively to just copy CMakeAutoGenScript.cmake into the sqlite folder but that didn't work either.

I also tried to build a shared lib from libsndfile (the app is destined will need to have libsndfile as a shared lib) using another sample app as the template: https://github.com/android/ndk-samples/tree/master/hello-libs which comprise a "lib generator". Modifying the code I successful build the libsndfile 1.1.0 (I hava a libsndfile.so) but the lib is not working as expected: it seem the generation of sndfile.h got screwed up (all the sf_count are "unknown"). I have to say that I bluntly added SHARED as the second argument of the libsndfile static build block:
```
add_library (sndfile
		SHARED
	src/sfconfig.h
        etc...
```

and added this block at the end of the "static"(now shared) build which replicate the others install in the sample app:
```
## copy out the lib binary and remove generated files
set(distribution_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../../../distribution)
set_target_properties(sndfile
		PROPERTIES
		LIBRARY_OUTPUT_DIRECTORY
		"${distribution_DIR}/libsndfile/lib/${ANDROID_ABI}")
add_custom_command(TARGET sndfile POST_BUILD
		COMMAND "${CMAKE_COMMAND}" -E
		copy "${CMAKE_CURRENT_SOURCE_DIR}/include/sndfile.hh"
		"${distribution_DIR}/libsndfile/include/sndfile.hh"
		COMMENT "Copying libsndfile to output directory")
```
That last command give file or directory not found so I commented out and copied manually sndfile.hh at the proper place but now cannot find <sndfile.h>.

So if you could help to get me some more proper arguments instead of trying blindly that will be highly appreciated. I thing those two sample apps are good starting point to get both static and shared build of libsndfile for android. Once I got that I'll tackle building with mpg123 and flac.

**Comment by evpobr** [comment]
Hi @scar20 . This is not correct:

```
### ADD LIBSNDFILE LIBRARY
set(LIB_SND_FILE_DIR ../../../../libsndfile)
add_subdirectory(${LIB_SND_FILE_DIR} ./sndfile)
include_directories(${LIB_SND_FILE_DIR}/include)
```

Try

```cmake
add_subdirectory(${LIB_SND_FILE_DIR} ./sndfile)
```

Then in your project:

```cmake
target_link_libraries(<yourtarget> PRIVATE SndFile::sndfile)
```

That's all. CMake will add libsndfile as dependency to <yourproject> and will do all the work you try to do manually.

**Comment by scar20** [comment]
Thanks for fast answer. I could not remove the line `set(LIB_SND_FILE_DIR ../../../../libsndfile)` since I got 
`add_subdirectory given source "./sndfile" which is not an existing directory.` if I do.

I removed the include_directory line and added the PRIVATE parameter in target_link_library as you said but I got the same error:
`ninja: error: 'C:/Users/Sylvain/AndroidStudioProjects/libsndfileProjects/SndFileLib2/libsndfile/cmake/sqlite/CMakeAutoGenScript.cmake', needed by 'sndfile/tests/utils.c', missing and no known rule to make it`

**Comment by evpobr** [comment]
Do you use latest libsndfile from repo?

**Comment by scar20** [comment]
Yes, from a few days ago
If it can help, here is the project structure
<SndFileLib2>    - project root
    <App>
        <src>
            <main>
                <cpp>
                    CMakeLists.txt --->entry point cmake file called by gradle, contains the aforementioned cmake command
                    native-lib.cpp
                <java>
        build.gradle ----> gradle file to build App module, call src/main/cpp/CMakeLists.text
    <gradle>
    <libsndfile> ----> latest libsndfile tree pointed by entry point CMakeLists.text

Included entry point CMakeLists.txt - there is not very much in it
[CMakeLists.txt](https://github.com/libsndfile/libsndfile/files/8008423/CMakeLists.txt)

**Comment by scar20** [comment]
Sorry I messed up the tree, here again:
```
<SndFileLib2>
  <App>
    <src>
      <main>
        <cpp>
          CMakeLists.txt --->entry point cmake file called by gradle, contains the aforementioned cmake command
          native-lib.cpp
    build.gradle ----> gradle file to build App module, call src/main/cpp/CMakeLists.text
  <gradle>
  <libsndfile> ----> latest libsndfile tree pointed by entry point CMakeLists.text
```

**Comment by evpobr** [comment]
Sorry, have no idea how to help you here. I don't know Java very well.

**Comment by scar20** [comment]
No need for java, its strictly cmake stuff - which I know about 1%.
Good news is that I've been able to build both static lib included in project, and shared lib used by project. Static lib had build quite readily, and I struggled many days with the shared build essentially to copy the headers at the right place. I finally go it with (I know it is hackish but all others command didn't work):
```
configure_file(${CMAKE_CURRENT_BINARY_DIR}/src/sndfile.h ${distribution_DIR}/libsndfile/include)
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/src/sndfile.hh ${distribution_DIR}/libsndfile/include)
```
Both build are from libsndfile version: libsndfile-1.0.29pre1. <---- called from my java method!

Now I want to do the same with v. 1.1.0 but it seem from the errors that there is a missing file in libsndfile/cmake/sqlite. The libsndfile CMakeText.txt get called by either gradle or the entry point CMakeText.txt depending of the setup with all the variables/propriety needed for android by default. You can also pass more specific command if needed.

Just tell me what command you would need me to try to get a more sensible picture of what is happening - is there a kind of verbose option for cmake? Perhaps there is a command to catch up what flags and parameters are passed by the entry point cmake file. We are very close of an easy solution for android build. If you can help here, I'll work very hard on my side to get all the others packages built in all the abi's - I need them too.

**Comment by evpobr** [comment]
`C:/Users/Sylvain/AndroidStudioProjects/libsndfileProjects/SndFileLib2/libsndfile/cmake/sqlite/CMakeAutoGenScript.cmake`

This path is wrong, it should be:

`C:/Users/Sylvain/AndroidStudioProjects/libsndfileProjects/SndFileLib2/libsndfile/cmake/CMakeAutoGenScript.cmake`

This line in my `CMakeLists.txt`

```
list (APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
```

adds `cmake` subdirectory relative to project directory with some CMake scripts including `CMakeAutoGenScript.cmake`. We use it to generate test sources.

There is also

```
if (CMAKE_VERSION VERSION_LESS 3.14)
	list (APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/sqlite")
endif ()
```

which adds path to CMake script that searches SQLite3 library if CMake version <= 3.14 (newer CMake version have that FindSQLIte module).

But I still don't understand at all why these paths broke down. Now I tried to remove the condition so that both paths are added - everything works.

Try to disable testring using `BUILD_TESTING` option set to `OFF` and upgrade CMake to newer version if you can. Just wondering if this will help.

Also try to replace `${CMAKE_CURRENT_SOURCE_DIR}` with `${PROJECT_SOURCE_DIR}` here:

```
list (APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
list (APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
if (CMAKE_VERSION VERSION_LESS 3.14)
	list (APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/sqlite")
endif ()
```

**Comment by scar20** [comment]
Yes. `BUILD_TESTING OFF` work. Changing `${CMAKE_CURRENT_SOURCE_DIR}` to `${PROJECT_SOURCE_DIR}` doesn't make a difference; still got the same error message. But adding `set (BUILD_TESTING OFF)` just before the `if (BUILD_SHARED_LIBS AND BUILD_TESTING)` block and it compile fine. Now I'm in the process of finding out what exactly is passed as arguments from the gradle plug-in to the initial CMakeLists.txt. Perhaps there could be conflict between those properties and the ones in libsndfile. BTW cmake is version 3.18.1and is from the IDE.

I've also got a hint of this as I build the shared version since `option (BUILD_SHARED_LIBS "Build shared libraries" ON)` set `BUILD_TESTING OFF` as a side effect and it built fine. My only problem with this version was to extract/copy the headers which I begin to understand should be done via some preset properties - I spotted:
```
target_include_directories (sndfile
	PUBLIC
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
		$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/include>
		$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
	PRIVATE
		src
		$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/src>
	)
```
which look like something that could of use. Need to study more those command. The idea would be to have a `ANDROID` target that will install those file at the `<user defined>` proper places. For the shared version I just added this at the end of the `if (BUILD_SHARED_LIBS)` block:
```
# copy out the lib binary and remove generated files
set(distribution_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../../../distribution)
set_target_properties(sndfile
		PROPERTIES
		LIBRARY_OUTPUT_DIRECTORY
		"${distribution_DIR}/libsndfile/lib/${ANDROID_ABI}")
make_directory("${distribution_DIR}/libsndfile/include")
configure_file(${CMAKE_CURRENT_BINARY_DIR}/src/sndfile.h ${distribution_DIR}/libsndfile/include)
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/include/sndfile.hh ${distribution_DIR}/libsndfile/include)
```
I dont like to hack inside this file like that but first step is having something to work, then make it more conform. I'm grateful for your help since I'm clearly newbie in this area so I dont want to abuse.

**Comment by evpobr** [comment]
I have reproduced this bug and will add fix.

**Comment by scar20** [comment]
Closing this since found a better way to build libsndfile + all external libs; cross compile on a virtual machine.
