### ISSUE TITLE
MP3 related CMake files are missing from 1.1.0 release package

### ISSUE THREAD

**Issue by alexey-lysiuk** [libsndfile/libsndfile#816]
There are two files `cmake/FindLame.cmake` and `cmake/FindMpg123.cmake` missing from [libsndfile-1.1.0.tar.xz](https://github.com/libsndfile/libsndfile/releases/download/1.1.0/libsndfile-1.1.0.tar.xz).
These files are present in the repository at the corresponding release tag.

**Comment by evpobr** [comment]
Hi @alexey-lysiuk , thanks for report.
