### ISSUE TITLE
What is SF_INFO sections used for?

### ISSUE THREAD

**Issue by cevans01** [libsndfile/libsndfile#817]
The API documentation says:

>  When opening a file for read, the format field should be set to zero before calling sf_open(). The only exception to this is the case of RAW files where the caller has to set the samplerate, channels and format fields to valid values. All other fields of the structure are filled in by the library.

> When opening a file for write, the caller must fill in structure members samplerate, channels, and format. 

But there is no indication of what `sections` is used for. I searched the rest of the API guide, the FAQ, and did an internet search but couldn't find anything.

From the source, it looks like this field is unconditionally being set to `1`, is that right?

https://github.com/libsndfile/libsndfile/blob/master/src/sndfile.c#L3049

**Comment by evpobr** [comment]
Hi @cevans01. Yes, as far as I know, this field is not used in any other way in the code.

**Comment by arthurt** [comment]
Yes, it is currently unused. I think only @erikd knows what the original plans for it are. I can think of a few good uses for it in future functionality expansions of libsndfile though.

For example the supported XI instrument major format can store multiple samples, and these individual samples are like individual sound files. The segments could perhaps related this. Another example is Ogg files with multiple concurrent streams, or concatenated streams. Or telephony prompt-set files (NMS Vox), which have collections of samples.

**Comment by evpobr** [comment]
Closed as answered.
