### ISSUE TITLE
[1.1.0] `pkg-config --static --libs sndfile` output contains `@EXTERNAL_MPEG_LIBS@`

### ISSUE THREAD

**Issue by cho-m** [libsndfile/libsndfile#827]
`@EXTERNAL_MPEG_LIBS@` is retained in generated pkgconfig file and leads to some commands outputting it like:
```console
$ pkg-config --static --libs sndfile | xargs printf "%s\n"
-L/usr/local/Cellar/libsndfile/1.1.0/lib
-L/usr/local/Cellar/flac/1.3.4/lib
-L/usr/local/Cellar/libvorbis/1.3.7/lib
-L/usr/local/Cellar/libogg/1.3.5/lib
-L/usr/local/Cellar/opus/1.3.1/lib
-lsndfile
@EXTERNAL_MPEG_LIBS@
-lFLAC
-lm
-lvorbisenc
-lvorbis
-lm
-logg
-lopus
```

In commit https://github.com/libsndfile/libsndfile/commit/85aea74e578d6f33c733ebdb775299bc39df2a02, `EXTERNAL_MPEG_LIBS` and `EXTERNAL_MPEG_REQUIRE` were added but only `EXTERNAL_MPEG_REQUIRE` has substitution.

I think the lack of `AC_SUBST(EXTERNAL_MPEG_LIBS)` in configure.ac results in following being retained:
https://github.com/libsndfile/libsndfile/blob/83e583dd2c69f0c43b8b7e822e9693b1277eb668/sndfile.pc.in#L12

**Comment by evpobr** [comment]
Hi @cho-m , thank you for bug report. Can you check your fix?

**Comment by cho-m** [comment]
I only checked Homebrew use-case without mpeg feature and it seems to work.

Applying a fix like
```patch
--- a/configure.ac
+++ b/configure.ac
@@ -739,6 +739,7 @@ AC_SUBST(SNDIO_LIBS)
 AC_SUBST(EXTERNAL_XIPH_CFLAGS)
 AC_SUBST(EXTERNAL_XIPH_LIBS)
 AC_SUBST(EXTERNAL_XIPH_REQUIRE)
+AC_SUBST(EXTERNAL_MPEG_LIBS)
 AC_SUBST(EXTERNAL_MPEG_REQUIRE)
 AC_SUBST(MPG123_CFLAGS)
 AC_SUBST(MPG123_LIBS)
```

And rebuilding, I get a blank `Libs.private` as expected (previously contained unwanted `@EXTERNAL_MPEG_LIBS@`). Haven't checked feature enablement.
```
prefix=/usr/local/Cellar/libsndfile/1.1.0
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: sndfile
Description: A library for reading and writing audio files
Requires:
Requires.private: flac ogg vorbis vorbisenc opus 
Version: 1.1.0
Libs: -L${libdir} -lsndfile
Libs.private: 
Cflags: -I${includedir}
```

**Comment by cho-m** [comment]
Tested with `mpg123` & `lame` and result does include substituted value. Will open PR.
```
prefix=/usr/local/Cellar/libsndfile/1.1.0
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: sndfile
Description: A library for reading and writing audio files
Requires:
Requires.private: flac ogg vorbis vorbisenc opus libmpg123
Version: 1.1.0
Libs: -L${libdir} -lsndfile
Libs.private: -lmp3lame
Cflags: -I${includedir}
```
