### ISSUE TITLE
Test suite failure on x86_64-musl

### ISSUE THREAD

**Issue by lun-4** [libsndfile/libsndfile#830]
Hello! I've been trying to update libsndfile from 1.0.31 to 1.1.0 in Void Linux, and I found this failure as its CI attempted to compile and test it for an x86_64 system using the musl libc. At the first time I upgraded, the test suite failed due to missing `libmpg123` and `liblame` (it was saying it wasn't compiled with MP3 support, which makes sense), after adding them both, I find the following error:

Reference for the update patch itself: https://github.com/void-linux/void-packages/pull/36908

Reference for the failing test suite: https://github.com/void-linux/void-packages/runs/6222001344?check_suite_focus=true

```
    pcm_test_int                   : wrt_32bit.sd2 ........... Note: Illegal Audio-MPEG-Header 0x00001831 at offset 9140.
Note: Trying to resync...
Note: Skipped 4 bytes in input.
Note: Illegal Audio-MPEG-Header 0x00005280 at offset 9148.
Note: Trying to resync...
Note: Skipped 28 bytes in input.
Note: Illegal Audio-MPEG-Header 0x00002207 at offset 9188.
Note: Trying to resync...
Note: Skipped 4 bytes in input.
Note: Illegal Audio-MPEG-Header 0x0000180b at offset 9196.
Note: Trying to resync...
Note: Skipped 16 bytes in input.
Note: Illegal Audio-MPEG-Header 0xffffeda8 at offset 9216.
Note: Trying to resync...
Note: Skipped 1 bytes in input.


Line 4535 : Stereo : sf_seek (file, 7091, SEEK_SET) returned 20915 (should be 7091).
```

I don't use the musl libc myself, but does that error make sense with a libc change?

**Comment by evpobr** [comment]
@lun-4 .

@arthurt , can you look at this please?

**Comment by arthurt** [comment]
When a test fails, the audio fail used in the test is not deleted. Could you check your working directory for a *.mp3 file that the failed test created and attach it here? Thanks!

**Comment by lun-4** [comment]
There isn't a `.mp3` file inside the build directory, but here's `wrt_32bit.sd2`, since that's the file being referenced in the failing test. file(1) can't identify it as an mp3 either, it's just "data".

[libsndfile_failing_test.zip](https://github.com/libsndfile/libsndfile/files/8591931/libsndfile_failing_test.zip)

**Comment by arthurt** [comment]
Okay, I have a theory.

SD2 files use a Classic Mac OS "resource fork" to store file metadata, including all headers, while the actual file is just raw PCM. (On non-MacOS filesystems and OS's, resource forks are emulated using a `._` prefixed file in the same directory.)

Libsndfile identifies the type of a file in `guess_file_type()` using the "magic" contents at the start of the file, then if there is no match, using the file extension for raw-types, and finally for the presence of a resource fork.

MP3 files don't really have any magic, but they do have a MPEG sync frames, which has a mostly detectable structure, but is only three bytes, beginning with 0xFFF.

What is happening is the .SD2 file `wrt_32bit.sd2` happens to start with data which looks enough like a MPEG sync frame that both libsndfile, and libmpg123 (which libsndfile uses) identify it as one. `guess_file_type()` returns that the file is an MPEG file before before noticing the extension and the resource fork.

I hypothesize that the reason this has not happened before is differences in the random number or math implementations of libc used to generate the short test files.

**Comment by arthurt** [comment]
A fix for this issue would be to move the attempt to identify a file as MP3 based on a MPEG sync frame to after looking for a resource fork, to avoid the false positives that are causing this issue.

Considering the lack of real magic values at the start of MPEG files, I think this is a good idea.

**Comment by lun-4** [comment]
If you want a setup to reproduce the issue while developing, I quickly put together the following steps:
 - Install Docker
 - Clone https://github.com/void-linux/void-docker
 - Apply the following patch (to be upstreamed by me soon)
```diff
diff --git a/Dockerfile.bootstrap b/Dockerfile.bootstrap
index 700571f..ad21f99 100644
--- a/Dockerfile.bootstrap
+++ b/Dockerfile.bootstrap
@@ -7,13 +7,14 @@ RUN apk add ca-certificates curl && \
   curl ${REPOSITORY}/static/xbps-static-static-0.59_5.$(uname -m)-musl.tar.xz | \
         tar vJx && \
         rm -f /etc/ssl/certs/2e5ac55d.* && \
-  if [ "${ARCH%-musl}" = "aarch64" ]; then \
-    export REPOSITORIES="--repository=${REPOSITORY}/current/aarch64"; \
-  elif [[ "${ARCH}" = "*-musl" ]]; then \
-    export REPOSITORIES="--repository=${REPOSITORY}/current/musl"; \
-  else \
-    export REPOSITORIES="--repository=${REPOSITORY}/current"; \
-  fi; \
+  case "${ARCH}" in \
+    aarch64*) \
+        export REPOSITORIES="--repository=${REPOSITORY}/current/aarch64" ;; \
+    *-musl) \
+        export REPOSITORIES="--repository=${REPOSITORY}/current/musl" ;; \
+    *) \
+        export REPOSITORIES="--repository=${REPOSITORY}/current" ;; \
+  esac; \
   XBPS_ARCH=${ARCH} xbps-install.static -yMU \
     $REPOSITORIES \
     -r /target \
diff --git a/Dockerfile.full b/Dockerfile.full
index b0f05b2..02ed5ff 100644
--- a/Dockerfile.full
+++ b/Dockerfile.full
@@ -5,13 +5,14 @@ COPY keys/* /target/var/db/xbps/keys/
 ARG REPOSITORY=https://repo-us.voidlinux.org
 ARG ARCH=x86_64
 RUN \
-        if [ "${ARCH%-musl}" = "aarch64" ]; then \
-                export REPOSITORIES="--repository=${REPOSITORY}/current/aarch64"; \
-        elif [[ "${ARCH}" = "*-musl" ]]; then \
-                export REPOSITORIES="--repository=${REPOSITORY}/current/musl"; \
-        else \
-                export REPOSITORIES="--repository=${REPOSITORY}/current"; \
-        fi; \
+        case "${ARCH}" in \
+        aarch64*) \
+            export REPOSITORIES="--repository=${REPOSITORY}/current/aarch64" ;; \
+        *-musl) \
+            export REPOSITORIES="--repository=${REPOSITORY}/current/musl" ;; \
+        *) \
+            export REPOSITORIES="--repository=${REPOSITORY}/current" ;; \
+        esac; \
         XBPS_ARCH=${ARCH} xbps-install -yMUS \
         $REPOSITORIES \
         -r /target \
```
 - Run `docker build --build-arg ARCH=x86_64-musl -t void-docker-bootstrap:latest -f Dockerfile.bootstrap .`
 - Run `docker build --build-arg ARCH=x86_64-musl --build-arg BOOTSTRAP_SOURCE=void-docker-bootstrap --build-arg BOOTSTRAP_VERSION=latest -t void-docker-full-x86_64-musl -f Dockerfile.full .`
 - Add the following into `Dockerfile.libsndfile`:
```dockerfile
FROM void-docker-full-x86_64-musl:latest
RUN xbps-install -y -Suv
RUN xbps-install -y pkg-config python3 git autogen autoconf automake libtool bash gcc make
RUN xbps-install -y alsa-lib-devel libvorbis-devel libflac-devel sqlite-devel opus-devel mpg123-devel lame-devel
RUN xbps-install -y alsa-lib libvorbis libflac sqlite opus mpg123 lame
RUN git clone https://github.com/libsndfile/libsndfile.git
RUN cd libsndfile && ./autogen.sh
RUN cd libsndfile && ./configure --enable-static
RUN cd libsndfile && make
RUN cd libsndfile && make check
```
 - Run `docker build -t void-docker-libsndfile -f Dockerfile.libsndfile .`
 - Reproduce the test failure after that one.
