### ISSUE TITLE
SF_INFO: int samplerate ?

### ISSUE THREAD

**Issue by fredvs** [libsndfile/libsndfile#844]
Hello.

**SF_INFO** is defined like this:
```
typedef struct
      {    sf_count_t  frames ;     /* Used to be called samples. */
           int         samplerate ;
           int         channels ;
           int         format ;
           int         sections ;
           int         seekable ;
       } SF_INFO ;
```

And **_samplerate_** is defined as _int_ (integer).

OK, but for other libraries, like _PortAudio_,  the **samplerate** is defined as _double_ (float).

I agree it should be rare to use a samplerate with decimals, but in case of...

**Comment by evpobr** [comment]
Hi @fredvs . No idea how to implement this without breaking API.

**Comment by fredvs** [comment]
Hello @evpobr.

OK, no problem, it is not important.

Thanks.

Fre;D
