### ISSUE TITLE
How to use sf_open_virtual to convert gsm to pcm then output byte array, don't save as file, any example?

### ISSUE THREAD

**Issue by jieny** [libsndfile/libsndfile#849]
i can read data from memory, but can't output as void* and don't know the converted file size. has any example?

**Comment by evpobr** [comment]
Hi @jieny :smile:

**Comment by jieny** [comment]
hi @evpobr

**Comment by jieny** [comment]
`

static sf_count_t vfwrite(const void *ptr, sf_count_t count, void *user_data) {
    VIO_DATA *vf = (VIO_DATA *) user_data;

    /*
    **	This will break badly for files over 2Gig in length, but
    **	is sufficient for testing.
    */
//    if (vf->offset >= sizeof(vf->data))
//        return 0;
//
//    if (vf->offset + count > sizeof(vf->data))
//        count = sizeof(vf->data) - vf->offset;

    memcpy(vf->data + vf->offset, ptr, (size_t) count);
    vf->offset += count;

    if (vf->offset > vf->length)
        vf->length = vf->offset;

    return count;
}

    VIO_DATA vio_dataOut;
    vio_dataOut.offset = 0;
    vio_dataOut.length = 0;
    vio_dataOut.data = (unsigned char *) malloc(200 * 1024);
    SNDFILE *outfile = sf_open_virtual(&vio, SFM_WRITE, &sfinfo, &vio_dataOut);

...

    FILE *pfOut = fopen("D:\\xxx.wav", "wb");
    fwrite(vio_dataOut.data, 1, vio_dataOut.length, pfOut);
    fclose(pfOut);
    free(vio_dataOut.data);
`

refer to https://github.com/libsndfile/libsndfile/blob/master/tests/virtual_io_test.c
