### ISSUE TITLE
Opus seems to ignore `SFC_SET_COMPRESSION_LEVEL`

### ISSUE THREAD

**Issue by arximboldi** [libsndfile/libsndfile#859]
I am trying to use `libsndfile` to encode Opus files. Excellent library!

My biggest caveat though is that it seems to ignore the compression level with Opus. It always uses something that seems to achieve something like 128 VBR. Not a bad default for this format, but it would be nice to be able to change it.

**Comment by evpobr** [comment]
Hi @arximboldi . What do you mean? `SFC_SET_COMPRESSION_LEVEL` doesn't work for you?

**Comment by arximboldi** [comment]
Correct. Regardless of the value, the files have the same size. It works properly with other codecs (Vorbis, MP3).

**Comment by evpobr** [comment]
Need more info: libsndfile version, OS.

**Comment by arximboldi** [comment]
With libsndfile 1.1.0, installed via Nix, both NixOS and MacOS.

https://github.com/NixOS/nixpkgs/blob/43c99bebdab0ed66de2c4264e48b25999c2d9573/pkgs/development/libraries/libsndfile/default.nix

**Comment by evpobr** [comment]
Cannot reproduce with Win64 official binaries.

[build.zip](https://github.com/libsndfile/libsndfile/files/9216315/build.zip)
[opus-test.zip](https://github.com/libsndfile/libsndfile/files/9216324/opus-test.zip)

**Comment by arximboldi** [comment]
Sorry for making you waste your time, I found a subtle issue in my code causing this.
