### ISSUE TITLE
Saving 8bit sample

### ISSUE THREAD

**Issue by Lulu04** [libsndfile/libsndfile#861]
Hi, first thank you for this awesome library !
This is not an issue, I have searched where to ask but not found. I apologize if this is not the right place to ask.

I am writing a FreePascal/Lazarus frontend to simplify the use of **OpenAL-Soft** combined with **LibSndFile**.

To write audio frames we can use :

-     sf_writef_short       to write 16bit sample
-     sf_writef_int           to write 32bit sample
-     sf_writef_float        to write float 32b
-     sf_writef_double    to write double 64b

But why there isn't a function to write signed char ? I ask because OpenAL is capable to mix directly in 8bits format, and I would to keep this possible.

Regards

**Comment by evpobr** [comment]
Hi @Lulu04 . You can create 8-bit WAV and write with any of these functions, libsndfile will convert input for you. We don't have `sf_writef_char()`, i do not know why, this is probably a very rare case.

**Comment by Lulu04** [comment]
I agree, 8bits audio is very rare.

So, in the case where OpenAL-Soft renders 8bit samples, we have to convert them to respectively, short, int, float or double before sending them to one of this functions.

I was just wondering why an 8bit version doesn't exists.
Thank you for your answer

Regards
