### ISSUE TITLE
test suite fails with "rounding errors" for many non-x86 architectures

### ISSUE THREAD

**Issue by umlaeute** [libsndfile/libsndfile#866]
i finally found the time to update the Debian package of `libsndfile` to 1.1.0, and after uploading to our build farm, the results are sobering.

while the build succeeds, the test suite does not for 12 out of 19 architectures.
of the 7 architectures that can successfully run the testsuite, 4 use a variant of the x86 CPU (x86, x86_64).

the failing architectures include `armhf` (of RaspberryPi fame) and `arm64` (people call it "the new thing").

here's a short tabular overview:

|arch | results |
|---|---|
|  [amd64](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=amd64&ver=1.1.0-1&stamp=1662500686&)          |  :tada:  |
|  [arm64](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=arm64&ver=1.1.0-1&stamp=1662500749&)          |  :boom:  |
|  [armel](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=armel&ver=1.1.0-1&stamp=1662501268&)          |  :boom:  |
|  [armhf](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=armhf&ver=1.1.0-1&stamp=1662500489&)          |  :boom:  |
|  [i386](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=i386&ver=1.1.0-1&stamp=1662500509&)            |  :tada:  |
|  [mips64el](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=mips64el&ver=1.1.0-1&stamp=1662500816&)    |  :boom:  |
|  [mipsel](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=mipsel&ver=1.1.0-1&stamp=1662501131&)        |  :boom:  |
|  [ppc64el](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=ppc64el&ver=1.1.0-1&stamp=1662500485&)      |  :boom:  |
|  [s390x](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=s390x&ver=1.1.0-1&stamp=1662512274&)          |  :boom:  |
|  [hppa](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=hppa&ver=1.1.0-1&stamp=1662502551&)            |  :tada:  |
|  [hurd-i386](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=hurd-i386&ver=1.1.0-1&stamp=1662507534&)  |  :tada:  |
|  [ia64](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=ia64&ver=1.1.0-1&stamp=1662501955&)            |  :boom:  |
|  [m68k](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=m68k&ver=1.1.0-1&stamp=1662505260&)            |  :tada:  |
|  [powerpc](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=powerpc&ver=1.1.0-1&stamp=1662506178&)      |  :boom:  |
|  [ppc64](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=ppc64&ver=1.1.0-1&stamp=1662502232&)          |  :boom:  |
|  [riscv64](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=riscv64&ver=1.1.0-1&stamp=1662502226&)      |  :boom:  |
|  [sh4](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=sh4&ver=1.1.0-1&stamp=1662504707&)              |  :tada:  |
|  [sparc64](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=sparc64&ver=1.1.0-1&stamp=1662508777&)      |  :boom:  |
|  [x32](https://buildd.debian.org/status/fetch.php?pkg=libsndfile&arch=x32&ver=1.1.0-1&stamp=1662501820&)              |  :tada:  |

the full logs can be found at https://buildd.debian.org/status/package.php?p=libsndfile

**EDIT**: note that the tests failed for the version `1.1.0-1` (more recent uploads, like `1.1.0-2` might have the issue fixed by patching the sources on the Debian side). I've updated the table to include direct links to the log files.

i have checked a few of them, and it seems they all fail because of some minor math imprecision.

at least, this is how i interpret errors like:
> Line 306 : Error at index 0, got -0.000935562, should be -0.000935563.
> Line 306 : Error at index 0, got -0.000935562, should be -0.000935562.
> Line 324 : Error at index 4, got  1.70062e-05, should be  1.70062e-05.

all these errors happen in the ` mpeg_stereo_seek_test`, which suggests that there's a comparision for exact equality (or at least, the epsilon is too small) when a lossy codec is involved...

in order for `libsndfile-1.1` to become part of Debian (and thus Ubuntu and whatnot), the test-suite *must* pass.

what shall I do?

**Comment by evpobr** [comment]
Hi @umlaeute , thanks for impressive testing.
