### ISSUE TITLE
sndfile.dll was not found

### ISSUE THREAD

**Issue by Stanlyhalo** [libsndfile/libsndfile#877]
I'm currently using premake to setup my visual studio project, and I have the include dir pointing towards the include folder, than I have the lib dir pointing towards the lib directory, and lastly I have the linked package `sndfile` which of course is the `sndfile.lib` file, but it seems there's a missing .dll file from the latest release of the win64 if I'm not mistaken? Because I'm getting this error message:
![image](https://user-images.githubusercontent.com/36088749/191155264-223e9b6b-27b7-42d7-a1bc-77eb581abfbf.png)

I could possible have overlooked something however, but I am just unaware to what I did wrong.

**Comment by Stanlyhalo** [comment]
And yes, I read the read me, but it seems the runtime library property is for setting it to multi-threaded and not anything relating to dynamic linking.

**Comment by evpobr** [comment]
Hi @Stanlyhalo . I'm not familiar with premake. Probably something wrong with you setup. The latest release contains dll of course, just checked just in case.

Windows generally has a big problem with dependencies in the absence of a standard package manager. The only option that works in any case is CMake and Vcpkg. Both technologies are natively supported by Visual Studio, so this is probably the easiest way.

**Comment by Stanlyhalo** [comment]
@evpobr Alright, I'll check, and also, premake is a tool that uses lua to set the configuration options, I personally use it to setup my visual studio projects, and I compile using msbuild (which is the tool used by vs compiler).

**Comment by Stanlyhalo** [comment]
Aha, I didn't realize the `.dll` file was in the bin folder, thanks for that heads up, it compiles now, thanks for the help.
