### ISSUE TITLE
autogen.sh fails on MacOS Monterey (macOS 12.6)

### ISSUE THREAD

**Issue by jfriesne** [libsndfile/libsndfile#878]
When I clone the libsndfile archive from github and run ./autogen on my Mac (running MacOS 12.6 Monterey) it fails with this output:

```
Jeremys-Mac-mini-2:libsndfile jaf$ ./autogen.sh 
checking for autogen ... yes
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... glibtoolize
checking for pkg-config ... yes
checking for python ... 
You must have Python installed to compile libsndfile.
Download the appropriate package for your distribution,
or get the source tarball at http://python.org/
no
Jeremys-Mac-mini-2:libsndfile jaf$ 
```

I think this is because MacOS no longer ships with an executable named "python"; rather it ships with "python3".   It would be good if the autogen.sh script was updated to check for python3 as well.

**Comment by evpobr** [comment]
Hi @jfriesne . @SoapGentoo , can you help?

**Comment by SoapGentoo** [comment]
@evpobr can we get rid of the `autogen.sh` script and tell people to just use `autoreconf -vif`? I'm tired of the boilerplate code and stuff like this.

**Comment by evpobr** [comment]
Of course, I've always liked the `autoreconf -vif` approach better.

**Comment by evpobr** [comment]
@SoapGentoo , will you take this issue?

**Comment by SoapGentoo** [comment]
yes, will do it later

**Comment by evpobr** [comment]
Ok
