### ISSUE TITLE
Failed to read some OPUS audio

### ISSUE THREAD

**Issue by veelion** [libsndfile/libsndfile#888]
we have a lot of OPUS audio, most of them can be read well, some got failed, but the failed OPUS can be played by Windows media player and mplayer.
The failed example is here: https://drive.google.com/file/d/1_3oFZl7Ruv64rAMRCWCpTR1QkAEtZJSo/view?usp=sharing

Using `sndfile-info` to check the audio, it can't get the `Frames` and `Duration`:
```
========================================
File : zz.opus
Length : 118784
Ogg stream data : Opus
Stream serialno : 409619929
Opus library version: libopus 1.3.1
Opus Header Metadata
  OggOpus version  : 1
  Channels         : 1
  Preskip          : 312 samples @48kHz
  Input Samplerate : 16000 Hz
  Gain             : 0.0
  Channel Mapping  : 0 (mono or stereo)
VorbisComment Metadata
  Vendor: libopus 1.1
  ENCODER=opusenc from opus-tools 1.1
  Granule pos offset  : 0

----------------------------------------
Sample Rate : 16000
Frames      : unknown
Channels    : 1
Format      : 0x00200064
Sections    : 1
Seekable    : TRUE
Duration    : unknown
```

**Comment by vadimkantorov** [comment]
It also happens often for webm files produced by chrome: https://stackoverflow.com/questions/73395207/how-to-get-duration-of-webm-video-file-when-duration-is-not-explicitly-defined

**Comment by vadimkantorov** [comment]
Maybe, Ogg container also has similar feature about not requiring duration to be set in header?

**Comment by tcwalther** [comment]
I encounter problems with reading OPUS as well.

Here's an audio file where reading works fine until you hit the last block:
[Opus_long.opus.zip](https://github.com/bastibe/python-soundfile/files/9946794/Opus_long.opus.zip)

Here's a short audio file that is short enough that also the first block fails.
[Opus_file.opus.zip](https://github.com/bastibe/python-soundfile/files/9946790/Opus_file.opus.zip)

Other opus files are seemingly read forever, and libsndfile never stops. Unfortunately, I only have examples of very long audio files where the latter happens, but here is one (at 35Mb, it's over Github's 25Mb file upload limit):
https://www.dropbox.com/s/0vbdu50vmeqnnp4/12%20HOUR%20STUDY%20WITH%20ME%20_%20No%20Music%20_%20Nature%20Breaks%20_%2050-10%20POMODORO%20%5BuXAArjLY0i0%5D.opus.ogg.zip?dl=0

**Comment by evpobr** [comment]
Thanks for report.

@arthurt , can you take a look?

**Comment by veelion** [comment]
`opusinfo`  (from https://opus-codec.org/release/dev/2018/09/18/opus-tools-0_2.html ) can read the file, and `opusdec` can decode the file to .wav 

```
Processing file "/tmp/zz.opus"...

New logical stream (#1, serial: 186a4dd9): type opus
Encoded with libopus 1.1
User comments section follows...
        ENCODER=opusenc from opus-tools 1.1
WARNING: EOS not set on stream 1 (normal for live streams)
Opus stream 1:
        Pre-skip: 312
        Playback gain: 0 dB
        Channels: 1
        Original sample rate: 16000 Hz
        Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
        Page duration:   1000.0ms (max), 1000.0ms (avg), 1000.0ms (min)
        Total data length: 116418 bytes (overhead: 2.51%)
        Playback length: 0m:26.993s
        Average bitrate: 34.5 kbit/s, w/o overhead: 33.64 kbit/s
```
