### ISSUE TITLE
latest release installable with package managers on Ubuntu

### ISSUE THREAD

**Issue by polinaeterna** [libsndfile/libsndfile#891]
Hey! I know that the latest version of `libsndfile` will be included in the official Ubuntu release [starting from version 23.04](https://bugs.launchpad.net/ubuntu/+source/libsndfile/+bug/1991492). But is it somehow possible to make it easily installable with package managers on older versions (Ubuntu 18+)?

**Comment by evpobr** [comment]
Hi @polinaeterna . Soppy, we do not build packages for operating systems. Perhaps with the release of a new DEB package, backports to older versions of Ubuntu will eventually appear. In the meantime, you can try alternative package managers, such as [Vcpkg](https://github.com/microsoft/vcpkg), [Conan](https://github.com/conan-io/conan) etc.
