### ISSUE TITLE
Please make a new release which includes #822

### ISSUE THREAD

**Issue by SpotlightKid** [libsndfile/libsndfile#892]
In #822 a fix was added, which allows CMake to properly detect Lame. Unfortunately that was merged after the last release. As a consequence, every Linux distro package of the latest release of libsndfile probably still misses MP3 support, even if Lame is installed at build time.

It would be very helpful to have a new patch release, so that other packages depending on libsndfile can finally rely on mp3 support being present.

**Comment by evpobr** [comment]
Hi @SpotlightKid . Release is planned.

**Comment by chenrui333** [comment]
Any update on this?

**Comment by evpobr** [comment]
@chenrui333 , it is ready.
