### ISSUE TITLE
Building libsndfile with `OGG` support only

### ISSUE THREAD

**Issue by erl987** [libsndfile/libsndfile#893]
I am trying to port an application that uses `OGG` to use `vcpkg` for dependency management. It turns out that it is only possible to install many third-party dependencies such as `MP3`, etc. together with the `OGG` support of `libsndfile` or none.

It boils down to the CMake configuration of `libsndfile`. There is only this flag to install `OGG` support, as far as I can see: `ENABLE_EXTERNAL_LIBS `

For licensing reasons, it is problematic to ship all these third-party dependencies that I am actually not using. It does not work to use this flag and then to delete the actually not used DLL files. `libsndfile` will refuse to run in this case.

Do you have any suggestions how I can configure `libsndfile` to only build using `OGG`—preferably using a dependency manager such as `vcpkg`?

Separately installing `libogg` in `vcpkg` and linking to it in the application does not seem to have the same effect as building `libsndfile` with `ENABLE_EXTERNAL_LIBS`.

**Comment by evpobr** [comment]
Hi @erl987 . Unfortunately, there is no way to enable `Ogg` only, it is secondary dependency of Vorbis, FLAC and Vorbis formats. Use `ENABLE_EXTERNAL_LIBS` to disable them all.

> Separately installing libogg in vcpkg and linking to it in the application does not seem to have the same effect as building libsndfile with ENABLE_EXTERNAL_LIBS.

Not sure i understand you, more info please.

**Comment by erl987** [comment]
Thanks, I think that is the info I needed.
