### ISSUE TITLE
OS X Tiger build fix

### ISSUE THREAD

**Issue by cellularmitosis** [libsndfile/libsndfile#918]
`programs/sndfile-play.c` attempts to include `Availability.h` on `__APPLE__`, but that file wasn't available until the Tiger (10.4) release of OS X.

It appears nothing from this file was needed, here is a patch which only includes it on OS X 10.5 and above:

```patch
--- libsndfile-1.0.28/programs/sndfile-play.c	2017-04-01 02:18:02.000000000 -0500
+++ libsndfile-1.0.28.patched/programs/sndfile-play.c	2023-02-26 00:22:44.000000000 -0600
@@ -61,7 +61,9 @@
 
 #elif (defined (__MACH__) && defined (__APPLE__))
 	#include <AvailabilityMacros.h>
+#ifdef MAC_OS_X_VERSION_10_5
 	#include <Availability.h>
+#endif
 
 #elif HAVE_SNDIO_H
 	#include <sndio.h>
```

(`MAC_OS_X_VERSION_10_5` will be defined on any system at 10.5 or above).

**Comment by evpobr** [comment]
Hi @cellularmitosis .

**Comment by evpobr** [comment]
Your sources are too old. This code was deleted, I can't say how long ago.

**Comment by cellularmitosis** [comment]
Ah thanks.  I followed the download link from the website which listed 1.0.28 as the latest, but it looks like 1.2.0 is the latest GitHub release.  Thanks!

http://www.mega-nerd.com/libsndfile/#Download
