### ISSUE TITLE
Unable to import soundfile in AWS lambda 

### ISSUE THREAD

**Issue by hsbaweja** [libsndfile/libsndfile#921]
Trying to import `python-soundfile` inside AWS lambda results in the following error. 
```
[ERROR] OSError: cannot load library 'libsndfile.so': /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/python/_soundfile_data/libsndfile.so)
```

Since I can't install linux packages inside lambda, I used the `whl` to install `soundfile` so that it includes it's own `libsndfile` and modified `LD_LIBRARY_PATH` to point to this `libsndfile.so` file.  

However it seems the `.so` file is too recent and incompatible with OS environment. 

I can see `libm-2.26.so` inside my lambda's /lib64/ folder, where can I find the compatible libsndfile.so for this?

**Comment by erikd** [comment]
You should ask your question in the appropriate repo: https://github.com/bastibe/python-soundfile
