### ISSUE TITLE
library versioning

### ISSUE THREAD

**Issue by 251** [libsndfile/libsndfile#944]
When I download and build version 1.2.0:

https://github.com/libsndfile/libsndfile/releases/download/1.2.0/libsndfile-1.2.0.tar.xz

I get a "libsndfile.so.1.0.35" - is that the intended behaviour?

**Comment by evpobr** [comment]
Hi @251 . Yes, it is expected. You see ABI version encoded in filename. API version is not the same.

**Comment by 251** [comment]
Thanks!
