### ISSUE TITLE
sf_open_fd() in release >=1.0.30 closes fd passed into it by caller on error, even if close_desc was false

### ISSUE THREAD

**Issue by brentr** [libsndfile/libsndfile#948]
In version 1.0.31, the sf_open_fd() function will close the file descriptor passed into it even if close_desc is false.
I believe the intent was to avoid leaking file descriptors, but the logic is flawed.  If the called passes in the fd, with
the instruction not to close it, it is a simple matter for the caller to do so if sf_open_fd() fails.
However, it may not always be possible to reopen the descriptor.

The function had been used by Debian's quickplot package (among others) to probe input files to determine whether or not they are audio files.  If they are not, quickplot parses them as tables of ASCII plot data.  The change in behavior was introduced in commit:

b329ba64ab625aa47c6aca58b88a29261ffb4137

This patch against the 1.0.31 release reverts it:

```
diff --git a/src/sndfile.c b/src/sndfile.c
index 63beda8d..607c6ebb 100644
--- a/src/sndfile.c
+++ b/src/sndfile.c
@@ -362,7 +362,6 @@ sf_open     (const char *path, int mode, SF_INFO *sfinfo)
 SNDFILE*
 sf_open_fd     (int fd, int mode, SF_INFO *sfinfo, int close_desc)
 {      SF_PRIVATE      *psf ;
-       SNDFILE         *result ;
 
        if ((SF_CONTAINER (sfinfo->format)) == SF_FORMAT_SD2)
        {       sf_errno = SFE_SD2_FD_DISALLOWED ;
@@ -384,15 +383,12 @@ sf_open_fd        (int fd, int mode, SF_INFO *sfinfo, int close_desc)
        copy_filename (psf, "") ;
 
        psf->file.mode = mode ;
+       psf->file.do_not_close_descriptor = !close_desc;
        psf_set_file (psf, fd) ;
        psf->is_pipe = psf_is_pipe (psf) ;
        psf->fileoffset = psf_ftell (psf) ;
 
-       result = psf_open_file (psf, sfinfo) ;
-       if (result != NULL && ! close_desc)
-                       psf->file.do_not_close_descriptor = SF_TRUE ;
-
-       return result ;
+       return psf_open_file (psf, sfinfo) ;
 } /* sf_open_fd */
 
 SNDFILE*

```

**Comment by evpobr** [comment]
Hi @brentr , thanks for report.

**Comment by evpobr** [comment]
Check #950 please.

**Comment by brentr** [comment]
Thank you for the quick response!
The proposed fix would work, but, I believe there is no longer any point to keeping this code:

```
if (result != NULL && ! close_desc)
                    psf->file.do_not_close_descriptor = SF_TRUE ;

```
Why not just simplify to:

`  return psf_open_file (psf, sfinfo) ;
`

after assigning do_not_close to the inverse of close_desc, as I suggested?

As I see it:
This function always returns the unmodified result of psf_openfile().
However, if that result is non-null and close_desc is false, you were setting the do_not_close flag (too late!)

The one line patch you propose correctly ensures that do_not_close will have already been set beforehand in this case.

So, what's the point of following with code that conditionally sets that same flag?

**Comment by evpobr** [comment]
Yes, thank you. Will fix it this weekend.
