### ISSUE TITLE
Consider dropping custom CMake SQLite module

### ISSUE THREAD

**Issue by diizzyy** [libsndfile/libsndfile#954]
For consistent handling it may be worth considering using upstream's variant?

SQLite3
https://github.com/Kitware/CMake/blob/master/Modules/FindSQLite3.cmake

**Comment by evpobr** [comment]
Hi @diizzyy 

Already there. Custom find module exists for CMake < 3.14:

https://github.com/libsndfile/libsndfile/blob/e486f20fd4b1c7490cde84f22635e1c267ae882b/CMakeLists.txt#L89-L91

**Comment by diizzyy** [comment]
True, looks like it's still needed for distros such as Debian 10(?) packaging ancient versions of CMake.
