### ISSUE TITLE
1.2.2 in vcpkg

### ISSUE THREAD

**Issue by hiccup7** [libsndfile/libsndfile#969]
I see that the latest release (2023.08.09) includes libsndfile 1.2.0:
https://github.com/microsoft/vcpkg/releases

I don't see any pull requests to update to libsndfile 1.2.2:
https://github.com/microsoft/vcpkg/pulls?q=libsndfile

Is a vcpkg update needed for downstream projects to build libsndfile 1.2.2?

**Comment by evpobr** [comment]
Hi @hiccup7 , forgot about that.

microsoft/vcpkg#34388

**Comment by evpobr** [comment]
Closed via microsoft/vcpkg/pull/34388
